import { regionalizeDeep } from './regional.ts'
import type { Locale } from './config.ts'

/**
 * Text for the free programme catalogue: the country pages with their search
 * and the pages per country and field. German is Swiss Standard German;
 * Germany and Austria get it regionalized, with their own fee notes.
 */

const IN_EN: Record<string, string> = { US: 'in the United States', GB: 'in the United Kingdom', KR: 'in South Korea' }
const IN_DE: Record<string, string> = {
  CH: 'in der Schweiz', DE: 'in Deutschland', AT: 'in Österreich', FR: 'in Frankreich', KR: 'in Südkorea', US: 'in den USA', GB: 'in Grossbritannien',
}

const en = {
  nav: 'Programmes',
  /** "in Switzerland"; `name` is the country's English name. */
  inCountry: (cc: string, name: string) => IN_EN[cc] ?? `in ${name}`,
  indexTitle: 'Degree programmes by country',
  indexLead: (n: string, c: number) => `${n} degree programmes in ${c} countries, from official sources and updated every week. Pick a country to search its programmes or browse them by field.`,
  indexMetaTitle: 'Degree programmes by country',
  indexMetaDesc: (n: string, c: number) => `Search ${n} degree programmes in ${c} countries by subject, university and city. Free, from official sources, updated every week.`,
  programmesShort: (n: string) => `${n} programmes`,
  institutionsShort: (n: string) => `${n} institutions`,
  metaTitle: (inC: string, n: string) => `All ${n} degree programmes ${inC}`,
  metaDesc: (inC: string, n: string, i: string) => `Search ${n} degree programmes at ${i} universities and colleges ${inC} by subject, university, city and degree. Free, updated every week, with a link to every programme.`,
  h1: (inC: string) => `Every degree programme ${inC}`,
  lead: (n: string, i: string, sources: string) => `${n} programmes at ${i} universities and colleges, from ${sources}. Search by subject, university or city, or start from a field below.`,
  updated: (date: string) => `Data from ${date}, refreshed every week.`,
  statProgrammes: 'Programmes',
  statInstitutions: 'Institutions',
  statFields: 'Fields',
  search: {
    label: 'Search programmes',
    placeholder: 'Subject, university or city',
    allLevels: 'All degrees',
    results: (n: string) => (n === '1' ? '1 programme' : `${n} programmes`),
    none: 'No programme matches. Try fewer or other words.',
    more: 'Show more',
    loading: 'Searching…',
    unavailable: 'The search goes live with the next weekly data update. Until then, browse the programmes by field below.',
    error: 'The search didn’t answer. Try again in a moment.',
    programme: 'Programme page',
    website: 'Website',
  },
  typesTitle: 'Kinds of institution',
  admission: 'Admission',
  fieldsTitle: 'Programmes by field',
  fieldsSub: (inC: string) => `Each field has its own page listing every programme ${inC}.`,
  institutionsTitle: 'Universities and colleges',
  institutionsSub: (n: number) => `The ${n} institutions with the most programmes.`,
  institutionsAll: 'Every institution in our data, by number of programmes.',
  feesTitle: 'What it costs',
  /** Per country; the English pages use the typical tuition in lib/countries.ts. */
  fees: {} as Record<string, string>,
  sourcesTitle: 'Where the data comes from',
  sourcesText: 'We read the official sources every week and sort each programme into one of our fields. Programme names and links come from the source; check the details with the university before you apply.',
  ctaTitle: 'Not sure which field is yours?',
  ctaText: 'The free test reads what you actually watch and search, plus a five-minute questionnaire, and tells you which fields fit. The full list of matching programmes, ranked for you with the fees for your citizenship, is a one-time purchase.',
  cta: 'Find my field',
  otherCountries: 'Other countries',
  // Country and field
  fieldMetaTitle: (f: string, inC: string, n: string) => `Study ${f} ${inC}: ${n} programmes`,
  fieldMetaDesc: (f: string, inC: string, n: string, i: string, levels: string) => `All ${n} ${f} programmes ${inC} at ${i} universities and colleges (${levels}), with degree, city, language and a link to each one.`,
  fieldH1: (f: string, inC: string) => `Study ${f} ${inC}`,
  fieldSummary: (f: string, inC: string, n: string, i: string, levels: string) => `${n} ${f} programmes ${inC} at ${i} universities and colleges: ${levels}.`,
  levelCount: (n: string, level: string) => `${n} ${level}`,
  moreAt: (n: string) => `${n} more at this institution`,
  searchIn: (f: string) => `Search ${f} programmes`,
  aboutTitle: (f: string) => `About ${f}`,
  aboutMore: (f: string) => `Who ${f} suits and where it leads`,
  careers: 'Where it leads',
  earningsCh: 'Median income one year after graduating',
  earningsUs: 'Median earnings of US graduates',
  admissionTitle: 'Who gets in',
  relatedTitle: (inC: string) => `Related fields ${inC}`,
  allProgrammes: (inC: string) => `All programmes ${inC}`,
  years: (n: string) => (n === '1' ? '1 year' : `${n} years`),
  modes: { 'full-time': 'Full-time', 'part-time': 'Part-time', both: 'Full- or part-time', distance: 'Distance learning' } as Record<string, string>,
  detail: {
    degree: 'Degree',
    institution: 'Institution',
    place: 'Location',
    language: 'Language of instruction',
    duration: 'Standard duration',
    mode: 'Study mode',
    focus: 'Focus',
    admission: 'Admission',
    fields: 'Fields',
    official: 'Official programme page',
    website: 'Institution website',
    title: 'Degree awarded',
    ects: 'Credits',
    deadline: 'Application deadline',
    requirements: 'Admission to this programme',
    prior: 'Admitting degrees',
    department: 'Department',
    partners: 'Run together with',
    otherLanguages: 'Also taught in',
    regulations: 'Study regulations',
  },
  linkCountryTitle: 'Search programmes',
  linkCountryText: (source: string) => `The individual programmes with all their details are listed by the official source, ${source}. Here you get the overview by field and institution.`,
  linkFieldTitle: (f: string, n: string) => `See all ${n} ${f} programmes`,
  linkFieldText: (source: string) => `Titles, places and details are listed by the official source, ${source}. The link opens its search for this field.`,
  linkOpen: (source: string) => `Open ${source}`,
  moreInstitutions: (n: string) => `and ${n} more institutions: use the search above.`,
  metaDescLink: (inC: string, n: string, i: string) => `${n} degree programmes at ${i} universities and colleges ${inC}, by field and institution, with admission and costs. Updated every week.`,
  fieldMetaDescLink: (f: string, inC: string, n: string, i: string, levels: string) => `${n} ${f} programmes ${inC} at ${i} universities and colleges (${levels}), by institution, with admission and costs.`,
  listSub: (n: string) => `All ${n} programmes with their exact title. Click one for degree, language, duration, focus, admission and links.`,
  fieldCtaTitle: (f: string) => `Is ${f} right for you?`,
}

export type CatalogueText = typeof en

const deCH: CatalogueText = {
  nav: 'Studiengänge',
  inCountry: (cc, name) => IN_DE[cc] ?? `in ${name}`,
  indexTitle: 'Studiengänge nach Land',
  indexLead: (n, c) => `${n} Studiengänge in ${c} Ländern, aus amtlichen Quellen und jede Woche aktualisiert. Wähl ein Land, um seine Studiengänge zu durchsuchen oder nach Fach zu stöbern.`,
  indexMetaTitle: 'Studiengänge nach Land',
  indexMetaDesc: (n, c) => `Durchsuche ${n} Studiengänge in ${c} Ländern nach Fach, Hochschule und Ort. Gratis, aus amtlichen Quellen, jede Woche aktualisiert.`,
  programmesShort: (n) => `${n} Studiengänge`,
  institutionsShort: (n) => `${n} Hochschulen`,
  metaTitle: (inC, n) => `Alle ${n} Studiengänge ${inC}`,
  metaDesc: (inC, n, i) => `Durchsuche ${n} Studiengänge an ${i} Hochschulen ${inC} nach Fach, Hochschule, Ort und Abschluss. Gratis, jede Woche aktualisiert, mit Link zu jedem Studiengang.`,
  h1: (inC) => `Alle Studiengänge ${inC}`,
  lead: (n, i, sources) => `${n} Studiengänge an ${i} Hochschulen, aus ${sources}. Such nach Fach, Hochschule oder Ort, oder fang bei einem der Fächer weiter unten an.`,
  updated: (date) => `Daten vom ${date}, jede Woche aktualisiert.`,
  statProgrammes: 'Studiengänge',
  statInstitutions: 'Hochschulen',
  statFields: 'Fächer',
  search: {
    label: 'Studiengänge durchsuchen',
    placeholder: 'Fach, Hochschule oder Ort',
    allLevels: 'Alle Abschlüsse',
    results: (n) => (n === '1' ? '1 Studiengang' : `${n} Studiengänge`),
    none: 'Kein Studiengang passt. Versuch es mit weniger oder anderen Wörtern.',
    more: 'Mehr anzeigen',
    loading: 'Suche läuft …',
    unavailable: 'Die Suche geht mit dem nächsten wöchentlichen Datenupdate online. Bis dahin findest du die Studiengänge unten nach Fach.',
    error: 'Die Suche hat nicht geantwortet. Versuch es gleich nochmals.',
    programme: 'Zum Studiengang',
    website: 'Website',
  },
  typesTitle: 'Hochschultypen',
  admission: 'Zulassung',
  fieldsTitle: 'Studiengänge nach Fach',
  fieldsSub: (inC) => `Jedes Fach hat eine eigene Seite mit allen Studiengängen ${inC}.`,
  institutionsTitle: 'Hochschulen',
  institutionsSub: (n) => `Die ${n} Hochschulen mit den meisten Studiengängen.`,
  institutionsAll: 'Alle Hochschulen in unseren Daten, nach Anzahl Studiengänge.',
  feesTitle: 'Was das Studium kostet',
  fees: {
    CH: 'An den Universitäten, der ETH und den Fachhochschulen zahlst du meist zwischen CHF 500 und 1’000 pro Semester. Studierende aus dem Ausland zahlen an manchen Hochschulen deutlich mehr. Dazu kommen Material, Wohnen und Leben, und die kosten in der Schweiz weit mehr als die Gebühren.',
    DE: 'Staatliche Hochschulen verlangen keine Studiengebühren. Du zahlst einen Semesterbeitrag von etwa 150 bis 400 Euro, oft mit Semesterticket. Baden-Württemberg und die TU München verlangen von Studierenden aus Ländern ausserhalb der EU Gebühren. Private Hochschulen kosten meist mehrere Hundert Euro im Monat.',
    AT: 'Öffentliche Universitäten sind für Studierende aus der EU gratis, solange du die Mindeststudiendauer pro Studienabschnitt um nicht mehr als zwei Semester überschreitest. Danach zahlst du rund 363 Euro pro Semester, Studierende aus Drittstaaten rund 727 Euro. Dazu kommt der ÖH-Beitrag. Fachhochschulen verlangen bis zu 363 Euro pro Semester, Privatuniversitäten deutlich mehr.',
  },
  sourcesTitle: 'Woher die Daten kommen',
  sourcesText: 'Wir lesen die amtlichen Quellen jede Woche neu und ordnen jeden Studiengang einem unserer Fächer zu. Namen und Links stammen aus der Quelle. Prüf die Details bei der Hochschule, bevor du dich anmeldest.',
  ctaTitle: 'Weisst du noch nicht, welches Fach zu dir passt?',
  ctaText: 'Der Gratistest liest, was du wirklich schaust und suchst, dazu kommen fünf Minuten Fragebogen. Danach weisst du, welche Fächer zu dir passen. Die volle Liste der passenden Studiengänge, sortiert nach deinem Profil und mit den Gebühren für deine Staatsbürgerschaft, gibt es als einmaligen Kauf.',
  cta: 'Mein Fach finden',
  otherCountries: 'Andere Länder',
  fieldMetaTitle: (f, inC, n) => `${f} studieren ${inC}: ${n} Studiengänge`,
  fieldMetaDesc: (f, inC, n, i, levels) => `${f} ${inC}: Alle ${n} Studiengänge an ${i} Hochschulen (${levels}), mit Abschluss, Ort, Sprache und Link zu jedem Studiengang.`,
  fieldH1: (f, inC) => `${f} studieren ${inC}`,
  fieldSummary: (f, inC, n, i, levels) => `${inC.charAt(0).toUpperCase()}${inC.slice(1)} gibt es ${n} Studiengänge in ${f} an ${i} Hochschulen: ${levels}.`,
  levelCount: (n, level) => `${n} ${level}`,
  moreAt: (n) => `${n} weitere an dieser Hochschule`,
  searchIn: (f) => `Studiengänge in ${f} durchsuchen`,
  aboutTitle: (f) => `Was du in ${f} lernst`,
  aboutMore: (f) => `Für wen ${f} passt und wohin es führt`,
  careers: 'Wohin es führt',
  earningsCh: 'Medianlohn ein Jahr nach dem Abschluss',
  earningsUs: 'Medianeinkommen von Absolventen in den USA',
  admissionTitle: 'Wer zugelassen wird',
  relatedTitle: (inC) => `Verwandte Fächer ${inC}`,
  allProgrammes: (inC) => `Alle Studiengänge ${inC}`,
  years: (n) => (n === '1' ? '1 Jahr' : `${n} Jahre`),
  modes: { 'full-time': 'Vollzeit', 'part-time': 'Teilzeit', both: 'Voll- oder Teilzeit', distance: 'Fernstudium' },
  detail: {
    degree: 'Abschluss',
    institution: 'Hochschule',
    place: 'Ort',
    language: 'Unterrichtssprache',
    duration: 'Regelstudienzeit',
    mode: 'Studienform',
    focus: 'Schwerpunkte',
    admission: 'Zulassung',
    fields: 'Fächer',
    official: 'Offizielle Seite des Studiengangs',
    website: 'Website der Hochschule',
    title: 'Titel',
    ects: 'Umfang',
    deadline: 'Anmeldeschluss',
    requirements: 'Zulassung zu diesem Studiengang',
    prior: 'Zulassende Vorstudien',
    department: 'Departement',
    partners: 'Gemeinsam mit',
    otherLanguages: 'Teilweise auch auf',
    regulations: 'Studienreglement',
  },
  linkCountryTitle: 'Studiengänge suchen',
  linkCountryText: (source) => `Die einzelnen Studiengänge mit allen Details führt die offizielle Quelle, ${source}. Hier findest du die Übersicht nach Fach und Hochschule.`,
  linkFieldTitle: (f, n) => `Alle ${n} Studiengänge in ${f} ansehen`,
  linkFieldText: (source) => `Titel, Orte und Details führt die offizielle Quelle, ${source}. Der Link öffnet dort die Suche nach diesem Fach.`,
  linkOpen: (source) => `${source} öffnen`,
  moreInstitutions: (n) => `und ${n} weitere Hochschulen: Nutze die Suche oben.`,
  metaDescLink: (inC, n, i) => `${n} Studiengänge an ${i} Hochschulen ${inC}, nach Fach und Hochschule, mit Zulassung und Kosten. Jede Woche aktualisiert.`,
  fieldMetaDescLink: (f, inC, n, i, levels) => `${f} ${inC}: ${n} Studiengänge an ${i} Hochschulen (${levels}), nach Hochschule, mit Zulassung und Kosten.`,
  listSub: (n) => `Alle ${n} Studiengänge mit genauem Titel. Ein Klick zeigt Abschluss, Sprache, Dauer, Schwerpunkte, Zulassung und Links.`,
  fieldCtaTitle: (f) => `Passt ${f} zu dir?`,
}

const IN_FR: Record<string, string> = { CH: 'en Suisse', DE: 'en Allemagne', AT: 'en Autriche', FR: 'en France', KR: 'en Corée du Sud', US: 'aux États-Unis', GB: 'au Royaume-Uni' }
const IN_IT: Record<string, string> = { CH: 'in Svizzera', DE: 'in Germania', AT: 'in Austria', FR: 'in Francia', KR: 'in Corea del Sud', US: 'negli Stati Uniti', GB: 'nel Regno Unito' }

const frCH: CatalogueText = {
  ...en,
  nav: 'Formations',
  inCountry: (cc, name) => IN_FR[cc] ?? `en ${name}`,
  programmesShort: (n) => `${n} formations`,
  institutionsShort: (n) => `${n} hautes écoles`,
  metaTitle: (inC, n) => `Les ${n} filières d’études ${inC}`,
  metaDesc: (inC, n, i) => `Recherche parmi ${n} filières d’études dans ${i} hautes écoles ${inC} par domaine, haute école, lieu et diplôme. Gratuit, mis à jour chaque semaine, avec un lien vers chaque formation.`,
  h1: (inC) => `Toutes les filières d’études ${inC}`,
  lead: (n, i, sources) => `${n} filières dans ${i} hautes écoles, d’après ${sources}. Cherche par domaine, haute école ou lieu, ou commence par un domaine ci-dessous.`,
  updated: (date) => `Données du ${date}, mises à jour chaque semaine.`,
  statProgrammes: 'Filières',
  statInstitutions: 'Hautes écoles',
  statFields: 'Domaines',
  search: {
    label: 'Rechercher une filière',
    placeholder: 'Domaine, haute école ou lieu',
    allLevels: 'Tous les diplômes',
    results: (n) => (n === '1' ? '1 filière' : `${n} filières`),
    none: 'Aucune filière ne correspond. Essaie avec moins de mots ou d’autres mots.',
    more: 'Afficher plus',
    loading: 'Recherche…',
    unavailable: 'La recherche sera disponible après la prochaine mise à jour hebdomadaire des données. En attendant, parcours les filières par domaine ci-dessous.',
    error: 'La recherche n’a pas répondu. Réessaie dans un instant.',
    programme: 'Page de la filière',
    website: 'Site web',
  },
  typesTitle: 'Types de hautes écoles',
  admission: 'Admission',
  fieldsTitle: 'Filières par domaine',
  fieldsSub: (inC) => `Chaque domaine a sa page avec toutes les filières ${inC}.`,
  institutionsTitle: 'Hautes écoles',
  institutionsSub: (n) => `Les ${n} hautes écoles qui proposent le plus de filières.`,
  institutionsAll: 'Toutes les hautes écoles de nos données, par nombre de filières.',
  feesTitle: 'Ce que coûtent les études',
  fees: {
    CH: 'Dans les universités, à l’EPF et dans les hautes écoles spécialisées, tu paies en général entre CHF 500 et 1’000 par semestre. Les étudiants venant de l’étranger paient nettement plus dans certaines hautes écoles. S’y ajoutent le matériel, le logement et la vie courante, qui coûtent en Suisse bien plus que les taxes.',
  },
  sourcesTitle: 'D’où viennent les données',
  sourcesText: 'Nous lisons les sources officielles chaque semaine et classons chaque filière dans l’un de nos domaines. Les noms et les liens viennent de la source. Vérifie les détails auprès de la haute école avant de t’inscrire.',
  ctaTitle: 'Tu ne sais pas encore quel domaine te convient?',
  ctaText: 'Le test gratuit lit ce que tu regardes et cherches vraiment, avec un questionnaire de cinq minutes, et te dit quels domaines te correspondent. La liste complète des filières, classées selon ton profil et avec les taxes pour ta nationalité, s’achète une seule fois.',
  cta: 'Trouver mon domaine',
  fieldMetaTitle: (f, inC, n) => `${f} ${inC} : ${n} filières`,
  fieldMetaDesc: (f, inC, n, i, levels) => `Les ${n} filières en ${f} ${inC} dans ${i} hautes écoles (${levels}), avec diplôme, lieu, langue et lien vers chaque filière.`,
  fieldH1: (f, inC) => `${f} : étudier ${inC}`,
  fieldSummary: (f, inC, n, i, levels) => `${n} filières en ${f} ${inC}, dans ${i} hautes écoles : ${levels}.`,
  moreAt: (n) => `${n} autres dans cette haute école`,
  searchIn: (f) => `Rechercher en ${f}`,
  aboutTitle: (f) => `Ce qu’on apprend en ${f}`,
  aboutMore: (f) => `À qui convient ${f} et où cela mène`,
  careers: 'Débouchés',
  earningsCh: 'Revenu médian un an après le diplôme',
  admissionTitle: 'Conditions d’admission',
  relatedTitle: (inC) => `Domaines proches ${inC}`,
  allProgrammes: (inC) => `Toutes les filières ${inC}`,
  years: (n) => (n === '1' ? '1 an' : `${n} ans`),
  modes: { 'full-time': 'Plein temps', 'part-time': 'Temps partiel', both: 'Plein temps ou temps partiel', distance: 'À distance' },
  detail: {
    degree: 'Diplôme',
    institution: 'Haute école',
    place: 'Lieu',
    language: 'Langue d’enseignement',
    duration: 'Durée réglementaire',
    mode: 'Forme d’études',
    focus: 'Orientations',
    admission: 'Admission',
    fields: 'Domaines',
    official: 'Page officielle de la filière',
    website: 'Site de la haute école',
    title: 'Titre délivré',
    ects: 'Crédits',
    deadline: 'Délai d’inscription',
    requirements: 'Admission à cette filière',
    prior: 'Études préalables admises',
    department: 'Département',
    partners: 'En collaboration avec',
    otherLanguages: 'Aussi enseigné en',
    regulations: 'Règlement d’études',
  },
  moreInstitutions: (n) => `et ${n} autres hautes écoles : utilise la recherche ci-dessus.`,
  listSub: (n) => `Les ${n} filières avec leur titre exact. Un clic affiche le diplôme, la langue, la durée, les orientations, l’admission et les liens.`,
  fieldCtaTitle: (f) => `${f}, est-ce fait pour toi?`,
}

const itCH: CatalogueText = {
  ...en,
  nav: 'Corsi',
  inCountry: (cc, name) => IN_IT[cc] ?? `in ${name}`,
  programmesShort: (n) => `${n} corsi`,
  institutionsShort: (n) => `${n} scuole universitarie`,
  metaTitle: (inC, n) => `Tutti i ${n} corsi di studio ${inC}`,
  metaDesc: (inC, n, i) => `Cerca tra ${n} corsi di studio in ${i} scuole universitarie ${inC} per materia, istituto, luogo e titolo. Gratis, aggiornato ogni settimana, con un link a ogni corso.`,
  h1: (inC) => `Tutti i corsi di studio ${inC}`,
  lead: (n, i, sources) => `${n} corsi in ${i} scuole universitarie, secondo ${sources}. Cerca per materia, istituto o luogo, oppure parti da una materia qui sotto.`,
  updated: (date) => `Dati del ${date}, aggiornati ogni settimana.`,
  statProgrammes: 'Corsi',
  statInstitutions: 'Scuole universitarie',
  statFields: 'Materie',
  search: {
    label: 'Cerca un corso di studio',
    placeholder: 'Materia, istituto o luogo',
    allLevels: 'Tutti i titoli',
    results: (n) => (n === '1' ? '1 corso' : `${n} corsi`),
    none: 'Nessun corso corrisponde. Prova con meno parole o con altre.',
    more: 'Mostra altri',
    loading: 'Ricerca…',
    unavailable: 'La ricerca sarà disponibile con il prossimo aggiornamento settimanale dei dati. Nel frattempo trovi i corsi per materia qui sotto.',
    error: 'La ricerca non ha risposto. Riprova tra un momento.',
    programme: 'Pagina del corso',
    website: 'Sito web',
  },
  typesTitle: 'Tipi di scuole universitarie',
  admission: 'Ammissione',
  fieldsTitle: 'Corsi per materia',
  fieldsSub: (inC) => `Ogni materia ha una pagina con tutti i corsi ${inC}.`,
  institutionsTitle: 'Scuole universitarie',
  institutionsSub: (n) => `Le ${n} scuole universitarie con più corsi.`,
  institutionsAll: 'Tutte le scuole universitarie nei nostri dati, per numero di corsi.',
  feesTitle: 'Quanto costa studiare',
  fees: {
    CH: 'Nelle università, al Politecnico federale e nelle scuole universitarie professionali paghi di solito tra CHF 500 e 1’000 a semestre. In alcuni istituti chi arriva dall’estero paga molto di più. Si aggiungono materiale, alloggio e vita quotidiana, che in Svizzera costano molto più delle tasse.',
  },
  sourcesTitle: 'Da dove vengono i dati',
  sourcesText: 'Leggiamo le fonti ufficiali ogni settimana e assegniamo ogni corso a una delle nostre materie. Nomi e link vengono dalla fonte. Verifica i dettagli presso l’istituto prima di iscriverti.',
  ctaTitle: 'Non sai ancora quale materia fa per te?',
  ctaText: 'Il test gratuito legge ciò che guardi e cerchi davvero, più un questionario di cinque minuti, e ti dice quali materie ti si addicono. La lista completa dei corsi, ordinata secondo il tuo profilo e con le tasse per la tua cittadinanza, si acquista una sola volta.',
  cta: 'Trova la mia materia',
  fieldMetaTitle: (f, inC, n) => `${f} ${inC}: ${n} corsi di studio`,
  fieldMetaDesc: (f, inC, n, i, levels) => `Tutti i ${n} corsi in ${f} ${inC} in ${i} scuole universitarie (${levels}), con titolo, luogo, lingua e link a ogni corso.`,
  fieldH1: (f, inC) => `Studiare ${f} ${inC}`,
  fieldSummary: (f, inC, n, i, levels) => `${n} corsi in ${f} ${inC}, in ${i} scuole universitarie: ${levels}.`,
  moreAt: (n) => `altri ${n} in questo istituto`,
  searchIn: (f) => `Cerca in ${f}`,
  aboutTitle: (f) => `Cosa si impara in ${f}`,
  aboutMore: (f) => `A chi si addice ${f} e dove porta`,
  careers: 'Sbocchi',
  earningsCh: 'Reddito mediano un anno dopo il diploma',
  admissionTitle: 'Chi viene ammesso',
  relatedTitle: (inC) => `Materie affini ${inC}`,
  allProgrammes: (inC) => `Tutti i corsi ${inC}`,
  years: (n) => (n === '1' ? '1 anno' : `${n} anni`),
  modes: { 'full-time': 'Tempo pieno', 'part-time': 'Tempo parziale', both: 'Tempo pieno o parziale', distance: 'A distanza' },
  detail: {
    degree: 'Titolo',
    institution: 'Istituto',
    place: 'Luogo',
    language: 'Lingua d’insegnamento',
    duration: 'Durata regolare',
    mode: 'Forma di studio',
    focus: 'Indirizzi',
    admission: 'Ammissione',
    fields: 'Materie',
    official: 'Pagina ufficiale del corso',
    website: 'Sito dell’istituto',
    title: 'Titolo rilasciato',
    ects: 'Crediti',
    deadline: 'Termine d’iscrizione',
    requirements: 'Ammissione a questo corso',
    prior: 'Studi precedenti ammessi',
    department: 'Dipartimento',
    partners: 'In collaborazione con',
    otherLanguages: 'Anche in',
    regulations: 'Regolamento di studio',
  },
  moreInstitutions: (n) => `e altre ${n} scuole universitarie: usa la ricerca qui sopra.`,
  listSub: (n) => `Tutti i ${n} corsi con il titolo esatto. Un clic mostra titolo di studio, lingua, durata, indirizzi, ammissione e link.`,
  fieldCtaTitle: (f) => `${f} fa per te?`,
}

const deDE = regionalizeDeep(deCH, 'de-DE')
const deAT = regionalizeDeep(deCH, 'de-AT')

export function catalogueText(locale: Locale): CatalogueText {
  return { en, 'de-CH': deCH, 'de-DE': deDE, 'de-AT': deAT, 'fr-CH': frCH, 'it-CH': itCH }[locale]
}
