import { AT_NAME, CH_NAME, DE_NAME } from './config.ts'
import { mergeDeep, regionalizeDeep } from './regional.ts'
import type { DeepPartial } from './regional.ts'
import type { Locale } from './config.ts'

/**
 * Interface text for both sites. German is Swiss Standard German: no ß,
 * «» quotes, CHF. Long-form pages (how it works, privacy, terms) are their own
 * components per language.
 */

const en = {
  nav: { how: 'How it works', fields: 'Fields', start: 'Start' },
  footer: {
    about: 'Your digital footprint plus a short questionnaire built on established interest and personality models, matched to fields of study and real programmes.',
    allFields: 'All fields of study',
    sources: 'Programme data sources',
    privacy: 'Privacy',
    terms: 'Terms',
    local: 'Analysis runs in your browser. We never see your history.',
    otherSites: 'Also for',
    siteNames: { global: 'International', ch: 'Switzerland', de: 'Germany', at: 'Austria' } as Record<string, string>,
    imprint: 'Imprint',
  },
  landing: {
    badge: 'Free · no sign-up · runs in your browser',
    h1a: 'What should you study?',
    h1b: 'Ask the',
    h1c: '10,000 choices',
    h1d: 'you’ve already made.',
    lead: (n: number) =>
      `Drop in your YouTube and Google history, your Instagram or TikTok export, and Reddit or GitHub if you like. Your browser reads them on your own device and counts which topics you keep coming back to. Add a short questionnaire on interests, school subjects and values, and you get your best fields out of ${n}, with matching programmes around the world. Nothing gets stored.`,
    cta: 'Find my field',
    cta2: 'How it works',
    totals: (p: string, i: string) => `${p} programmes at ${i} institutions, refreshed every week.`,
    marquee: 'fields to discover',
    cols: [
      ['Your footprint shows', 'what you actually spend your attention on, month after month. Years of history don’t care how a question is phrased.'],
      ['Quizzes ask', 'what you think you like. The answer depends on what sounds good and how you feel that day.'],
      ['We combine both', 'because a footprint can’t know your grades or your values. Each part covers the other’s blind spots.'],
    ] as Array<[string, string]>,
    sourcesTitle: 'Plug in what you like. Skip the rest.',
    sourcesSub: 'Every source is optional and read-only. The more you add, the sharper it gets.',
    sources: [
      { name: 'YouTube & Google', how: 'One request at Google, one file', what: 'Every video you watched, often years of it, plus your Google searches, the pages you visited, Maps and apps. The richest source by far.', n: '5,000–100,000 signals', color: 'pink' },
      { name: 'Spotify', how: 'Request it from Spotify, drop the file', what: 'Podcasts, saved episodes and audiobooks show what you want to understand. Music adds a light personality signal.', n: '200–20,000 signals', color: 'lime' },
      { name: 'Instagram & TikTok', how: 'Request it from Instagram or TikTok, drop the file', what: 'The topics Instagram filed you under, the accounts you follow, what you liked, saved and searched, your hashtags.', n: '300–20,000 signals', color: 'yellow' },
      { name: 'Reddit', how: 'Sign in, read-only', what: 'The communities you joined, what you saved and upvoted, what you posted. r/AskHistorians says a lot.', n: '100–3,000 signals', color: 'orange' },
      { name: 'GitHub', how: 'Just your username', what: 'What you build and what you star. The strongest signal there is for people who make things.', n: '20–600 signals', color: 'sky' },
      { name: 'Questionnaire', how: '5 minutes, all optional', what: 'Holland interests (RIASEC), the 20-item Mini-IPIP Big Five, your school subjects and what you want from work.', n: '60 answers', color: 'violet' },
    ],
    privacyTitle: 'Your data stays yours.',
    privacyBody:
      'The analysis runs in your browser. Sign-ins are read-only and their tokens never touch our server. Files you drop are unpacked on your device. What’s kept is a summary, in your browser, deleted with one click. To find programmes we only send your top fields and filters.',
    privacyPoints: ['We store nothing: no database, no account, no email', 'No tracking cookies', 'Read-only access you can revoke anytime', 'Raw history is thrown away after the analysis', 'Every step of the model is documented'],
    priceTitle: 'Free result. Full report when you’re ready.',
    free: 'Free',
    freeList: ['Your fields from place 2 down, with the evidence behind each', 'Hidden matches you’d never have checked', 'Interest profile (RIASEC) and Big Five', 'How your interests moved over the years', 'How many programmes match, and where'],
    full: 'Full report',
    oneTime: 'one-time · 12 months',
    fullList: ['Your #1 field, with all the evidence', 'Every matching programme, ranked for you', 'The tuition fee for your citizenship', 'Graduate earnings, debt and admission rates where published', 'Research-strong universities in 60+ countries', 'Filters, search, CSV export, new programmes flagged'],
    faqTitle: 'Questions',
    faq: [
      ['Do you store my YouTube history?', 'No. The analysis runs in your browser. Your history goes straight from Google to your device, gets turned into a summary and the raw data is thrown away. Our server never sees it.'],
      ['Is this a real psychological test?', 'The questionnaire uses established instruments: Holland’s RIASEC interest model, the basis of most career guidance, and the Mini-IPIP, a validated 20-item Big Five scale. The footprint analysis is our own model; the how-it-works page explains every step and its limits.'],
      ['Which countries do you cover?', 'Programme by programme: the United States, the United Kingdom, France and Switzerland, from official data. For 60+ other countries we show the universities strongest in your fields by research output, plus every university in the country.'],
      ['What does the full report add?', 'Your #1 field with all the evidence, and every matching programme in the countries you pick, with the fee that applies to you, graduate earnings where published, admission rates and links to apply. One payment, valid 12 months, data refreshed weekly.'],
      ['Can I use it without connecting anything?', 'Yes. The questionnaire alone gives a solid result. Each source you add makes it sharper, and the confidence badge on your result tells you how much it rests on.'],
    ] as Array<[string, string]>,
    finalCta: 'Start now, it’s free',
    next: 'Coming next from the same team: whatshouldiwork.',
    example: 'Example result',
    exampleSignals: '14,382 signals · 4 sources',
    code: 'Interest code',
    codeSub: 'Builder · Thinker · Organiser',
    exampleRows: [
      ['aerospace-engineering', 97, 'Everyday Astronaut, Scott Manley · 214 videos over 31 months'],
      ['mechanical-engineering', 94, 'Stuff Made Here, r/CNC · your 3 repos'],
      ['physics', 88, 'PBS Space Time · 2 podcasts'],
    ] as Array<[string, number, string]>,
    hiddenLabel: 'Hidden match:',
    hiddenText: 'Industrial Design. You rarely watch it, but your profile fits.',
    typesTitle: 'University, ETH, UAS or teacher education?',
    typesSub: 'Four kinds of higher education in Switzerland, with different admission rules.',
    typesCount: (n: number) => `${n} institutions`,
  },
  start: {
    title: 'Let’s find your field.',
    lead: 'Connect as many sources as you like, answer as much of the questionnaire as you want, then see your result. You can come back and add more anytime.',
    step1: 'Connect your sources',
    step1sub: 'Read-only. Analysed in your browser, nothing is uploaded.',
    step2: 'Five minutes about you',
    step2sub: 'What no history shows: how you see yourself, your subjects, your priorities. Every part is optional.',
    step3: 'Where and what',
    step3sub: 'Used to filter programmes and show the fees that apply to you.',
    yt: 'Your watch history, every video often going back years, plus what Google logs: your searches, pages you visited, Maps and apps. The richest source.',
    ytLogin: 'Or sign in for subscriptions and likes only, without the watch history:',
    spotify: 'Podcasts, saved episodes and audiobooks, plus your top artists for music taste.',
    reddit: 'Your communities, saved and upvoted posts, and what you wrote yourself.',
    github: 'What you build and what you star. Public data, just your username.',
    instagram: 'The topics Instagram files you under, the accounts you follow, your likes, saved posts and searches.',
    tiktok: 'Your searches, the accounts you follow, your hashtags and comments.',
    best: 'Best',
    signalsRead: (n: string) => `${n} signals read`,
    remove: 'Remove',
    refresh: 'Refresh',
    connect: (s: string) => `Connect ${s}`,
    notConfigured: (s: string) => `${s} sign-in isn’t set up on this deployment yet.`,
    request: {
      instagram: 'Request your Instagram data',
      tiktok: 'Request your TikTok data',
      spotify: 'Request your Spotify data',
      youtube: 'Request your history from Google',
    },
    hint: {
      instagram: 'Pick «Download to device» and «All time». A few minutes later an email brings the download.',
      tiktok: 'Choose «All data» and request it. TikTok lets you know as soon as the download is ready.',
      spotify: 'Request your «Account data». Spotify emails the download, which takes a few days.',
      takeout: [
        '«My Activity» is ticked already: YouTube watch and search history, Google searches, Maps and apps.',
        'Further down, tick «YouTube and YouTube Music» too. That adds subscriptions, comments and playlists.',
        '!Important: under YouTube, click «All YouTube data included» and untick «videos». Those are videos you uploaded yourself; we don’t need them and Google won’t let us untick them for you.',
        '«Next step», then «Create export».',
        'About 3 minutes later an email arrives: open it, scroll all the way down and press «Download». That file goes here.',
      ],
    },
    drop: 'When the email arrives: drop the file here',
    addAnother: 'Add or replace a file',
    takeoutPartMissing: (files: string) => `This is only Google’s table of contents: it lists ${files} files but holds none of them. Open takeout.google.com/manage (or the link in Google’s email), scroll all the way down and press «Download». The file you get then (often …-1-001.zip, much bigger) goes here.`,
    unread: (n: number, files: string) => `(${n} file${n === 1 ? '' : 's'} we couldn’t read: ${files})`,
    emptyTakeout: (products: string) => `This Google archive holds no history${products ? ` (only: ${products})` : ''}. Request it again with the button above, with «My Activity» ticked.`,
    optional: 'optional',
    spotifySlow: 'Spotify takes a few days to send it. Podcasts and audiobooks help your result, music only a little.',
    fileReady: 'File already there? Drop it here',
    dropSub: 'or click to choose · stays on your device',
    noHistory: 'Nothing usable in these files. The button above takes you to the right one.',
    githubPlaceholder: 'your-username',
    add: 'Add',
    localOnly: 'Everything above is stored only in this browser.',
    deleteAll: 'Delete all my data',
    deleteConfirm: 'Delete all your connected data, answers and preferences from this browser?',
    signals: 'signals',
    answers: 'answers',
    seeResult: 'See my result →',
    needMore: 'Connect a source or answer 18 questions',
  },
  q: {
    tabs: { interests: 'Interests', personality: 'Personality', subjects: 'School subjects', values: 'What matters' },
    hints: {
      interests: 'How much would you enjoy …',
      personality: 'How accurately does this describe you? «I …»',
      subjects: 'How much do you enjoy each subject, and how good are you at it?',
      values: 'How important is this to you in a future job?',
    },
    next: (t: string) => `Next: ${t} →`,
    ipipNote: 'Mini-IPIP (Donnellan et al., 2006), public-domain items from the International Personality Item Pool.',
    likertInterest: ['Dislike', 'Not really', 'Neutral', 'Like', 'Love'],
    likertAccuracy: ['Very inaccurate', 'Inaccurate', 'Neither', 'Accurate', 'Very accurate'],
    enjoy: 'Enjoy',
    goodAt: 'Good at',
    enjoyHead: 'Enjoy (1 = not at all)',
    goodHead: 'Good at (1 = weak)',
    enjoyScale: ['Not at all', 'A little', 'Somewhat', 'A lot', 'Love it'],
    goodScale: ['Weak', 'Below average', 'Average', 'Good', 'Excellent'],
    valueScale: ['Unimportant', 'Slightly', 'Moderately', 'Very', 'Essential'],
    riasec: null as Record<string, string> | null,
    big5: null as Record<string, string> | null,
  },
  prefs: {
    studying: 'Already studying something?',
    studyingHint: 'Then what you search and watch for it since then hardly counts. That’s coursework, not interest.',
    notStudying: 'No',
    since: 'Since',
    sinceUnknown: 'Since … (not sure)',
    sinceYear: (y: number) => `since ${y}`,
    level: 'Level',
    levels: { bachelor: 'Bachelor’s', master: 'Master’s', any: 'Both' },
    origin: 'Your citizenship',
    originHint: 'Decides which tuition fee applies.',
    origins: { eu: 'EU / EEA', ch: 'Switzerland', uk: 'United Kingdom', us: 'United States', other: 'Elsewhere' },
    maxFee: 'Maximum tuition per year',
    noLimit: 'No limit',
    english: 'Only programmes taught in English',
    where: 'Where would you study?',
    anywhere: 'Anywhere',
    clear: (n: number) => `Clear (${n})`,
    regions: { us: 'United States', uk: 'United Kingdom', eu: 'European Union', dach: 'Germany, Austria, Switzerland', nordics: 'Nordics', anglo: 'English-speaking' },
    withData: 'Every programme listed',
    withoutData: 'Strongest universities + full directory',
  },
  results: {
    calculating: 'Calculating …',
    nothingTitle: 'Nothing to analyse yet',
    nothingText: 'Connect a source or answer part of the questionnaire first.',
    signalsFrom: (n: string, s: string) => `${n} signals from ${s}`,
    yourAnswers: 'your answers',
    title: 'Your result',
    addMore: 'Add more data',
    confidence: { low: 'Low confidence: add a source or the questionnaire', medium: 'Medium confidence', high: 'High confidence' },
    confidenceTip: 'How much data and how many kinds of input the result rests on',
    best: 'Your best match',
    lockedTitle: 'Your #1 is ready',
    lockedText: 'It comes with the full report, together with every programme that matches your top fields.',
    lockedCta: 'Unlock place 1 ↓',
    lockedChip: 'Place 1',
    matchPct: (n: number) => `${n}% match`,
    yearRank: (n: number) => `Place ${n} that year`,
    relative: (n: number) => `match, compared with all ${n} fields`,
    leadsTo: 'Leads to',
    more: 'More about this field →',
    next: 'Your next best fields',
    why: 'Why?',
    less: 'Less',
    topics: 'Topics we matched',
    examples: (n: number) => `${n} examples from your data`,
    hiddenTitle: 'Hidden matches',
    hiddenSub: 'Fields you barely touch online, but your interests, personality and subjects fit them.',
    riasecTitle: 'Interest profile',
    riasecSub: (from: string, code: string) => `Holland’s RIASEC types, from ${from}. Your code: ${code}`,
    from: { questionnaire: 'the questionnaire', footprint: 'your footprint', and: ' and ' },
    big5Title: 'Personality',
    big5Sub: 'Big Five, compared with people your age.',
    big5Q: 'From your questionnaire.',
    big5Music: 'Estimated from your music taste only: a weak signal, take it lightly.',
    percentile: (n: number) => `${n}th percentile`,
    middle: 'In the middle',
    big5Missing: 'Answer the 20 personality questions (2 minutes) to include it.',
    addIt: 'Add it',
    insightsTitle: 'What your data says',
    timelineTitle: 'How your interests moved',
    timelineSub: 'Your top three fields each year, ranked, against what everyone watches.',
    timelineStudying: (field: string, since?: number) => `${field} is left out ${since ? `from ${since}` : 'here'}: you study it, so that’s coursework.`,
    components: { interest: 'What you engage with', riasec: 'Interest type fit', personality: 'Personality fit', subjects: 'School subjects', values: 'Your priorities' },
    kinds: {
      subscription: 'subscribed', like: 'liked', watch: 'watched', search: 'searched', google: 'googled', comment: 'commented', playlist: 'playlist', upload: 'your video',
      podcast: 'podcast', episode: 'episode', book: 'audiobook', subreddit: 'community', saved: 'saved', upvote: 'upvoted', post: 'your post',
      repo: 'your repo', fork: 'fork', star: 'starred', bio: 'bio', topic: 'topic',
    } as Record<string, string>,
  },
  reasons: {
    interest: (items: number, months: number) =>
      months > 1 ? `${items} things you watched, followed or saved are about this, spread over ${months} months.` : `${items} things you watched, followed or saved are about this.`,
    riasec: (types: string) => `Fits your ${types} side.`,
    subjects: (s: string) => `Builds on ${s}, which you enjoy.`,
    subjectsLow: (s: string) => `Leans heavily on ${s}, which you don’t enjoy much.`,
    values: (v: string) => `Offers what matters to you: ${v}.`,
    personality: (high: boolean, trait: string) => `Suits your ${high ? 'high' : 'low'} ${trait}.`,
    hidden: 'You rarely watch or read about this, but your profile fits it.',
    studying: (since?: number) =>
      since ? `You’ve studied this since ${since}. What you searched and watched about it since then hardly counts.` : 'You already study this, so what you search and watch about it hardly counts.',
    and: ' and ',
  },
  insights: {
    datapoints: { title: 'Signals analysed', detail: (s: number) => `From ${s} source${s === 1 ? '' : 's'}, entirely in your browser.` },
    learning: {
      title: 'Learning share',
      detail: (share: number): string =>
        share > 45
          ? 'A big part of what you consume is about understanding things. Good sign for academic study.'
          : share > 25
            ? 'A healthy mix of learning and entertainment.'
            : 'Mostly entertainment, so your questionnaire answers carry extra weight.',
    },
    breadth: {
      title: 'Curiosity style',
      value: { explorer: 'Explorer', specialist: 'Specialist', focused: 'Focused explorer' } as Record<string, string>,
      detail: (style: string, areas: number, spread: boolean) =>
        style === 'explorer'
          ? `You follow ${areas} different academic areas. Interdisciplinary programmes (liberal arts, cognitive science, PPE) deserve a look.`
          : style === 'specialist'
            ? 'Your interests sit in a few areas. A specialised programme will likely keep you hooked.'
            : `You go deep on a few areas and dip into ${areas} overall.${spread ? ' Your top three sit in different families, so a double major is worth a thought.' : ''}`,
    },
    consistency: {
      title: 'Staying power',
      value: { long: 'Long-term', recurring: 'Recurring', recent: 'Recent' } as Record<string, string>,
      detail: { long: 'Your top interests show up month after month, not just in phases. A strong sign they are real.', recurring: 'Your top interests come back regularly.', recent: 'Your top interests are fairly new. Worth checking they last.' } as Record<string, string>,
    },
    rhythm: {
      title: 'Daily rhythm',
      value: { owl: 'Night owl', early: 'Early bird', day: 'Daytime' } as Record<string, string>,
      detail: (peak: number, night: number) => `Your activity peaks around ${peak}:00${night > 20 ? `, and ${night}% happens between midnight and 5 am` : ''}. Just for fun, it doesn’t change your matches.`,
    },
    maker: { title: 'Maker', detail: (n: number) => `You don’t only consume: ${n} things you published or built. Project-based programmes will suit you.`, value: (n: number) => (n >= 10 ? 'Builder' : 'Creator') },
  },
  programmes: {
    title: 'Where to study it',
    sub: (where: string, level: string) => `Real programmes for your top fields${where}, ${level}.`,
    inCountries: (n: number) => ` in ${n} countries`,
    inList: (names: string[]) => ` in ${names.join(', ')}`,
    anywhere: ', anywhere we have data',
    levelText: { any: 'bachelor’s and master’s', master: 'master’s level', bachelor: 'bachelor’s level' },
    change: 'Change',
    demo: 'Demo data: this deployment shows a small sample until the weekly data workflow has run.',
    matchCount: 'programmes match your top fields and filters',
    freeTop: (n: number) => `Your top ${n}, free:`,
    loading: 'Looking up programmes …',
    boxTitle: 'Get the full report',
    boxSub: 'Your #1 field and every programme that matches your top fields, ranked for you.',
    boxList: (n: string) => ['Your #1 field, with all the evidence', `All ${n} matching programmes`, 'The fee for your citizenship', 'Earnings, debt and admission rates where published', 'Strongest universities in 60+ more countries', 'Filters, search and CSV export', 'New programmes flagged, refreshed weekly'],
    paymentsOff: 'Payments aren’t set up on this deployment yet.',
    unlockFree: 'Unlock (free in this deployment)',
    unlock: (p: string) => `Buy now · ${p}`,
    minors: 'Under 18? Please only buy with your parents’ consent.',
    opening: 'Opening checkout …',
    boxNote: 'One-time · valid 12 months · secure checkout by Stripe',
    row: { field: 'Field', level: 'Level', duration: 'Duration', yrs: 'yrs', fee: 'Tuition/yr', feeSemester: 'Tuition/semester', free: 'Free', approx: ' (approx.)', seePage: 'See programme page', openPage: 'Open the programme page', earnings: (y: number) => `Earnings ${y} yr after`, debt: 'Median debt', admission: 'Admission rate', places: 'Places', students: 'Students', language: 'Language', entry: 'Entry', isNew: 'New', matchTip: 'How well this programme matches your fields' },
    fit: {
      why: 'Fits you because of',
      example: 'e.g. you looked at',
      title: 'Why this programme fits you',
      intro: 'It names topics that keep coming up in your data:',
      inData: (n: string, sources: string) => `${n}× in your data (${sources})`,
      bonus: 'These topics move it up your list. The examples stay in your browser; only the topic words went to our server for sorting.',
    },
    details: {
      open: 'Details and why it fits you',
      close: 'Hide details',
      rank: (n: number, field: string) => `${field} is your number ${n}.`,
      items: (items: string, months: number) =>
        months > 1 ? `${items} of your videos, searches and posts are about it, over ${months} months.` : `${items} of your videos, searches and posts are about it.`,
      named: (terms: string[]) => `Your topics in its focus: ${terms.map((x) => `“${x}”`).join(', ')}.`,
      forYou: 'What in it fits you',
      noOverlap: (field: string) => `None of your topics appears in its description. It fits you through ${field} in general.`,
      onlyField: (field: string) => `We have no description of this programme yet, so it fits you through ${field} in general. The institution’s page lists its focus.`,
      noInfo: 'We have no description of this programme yet. The institution’s page lists what it focuses on.',
      fieldGeneral: (field: string) => `${field} and you`,
      focus: 'Focus',
      about: 'About the programme',
      also: (list: string[]) => `Also covers ${list.join(' and ')}.`,
      alsoRank: (field: string, n: number) => `${field} (your number ${n})`,
      topics: 'Your topics in this field',
      seen: 'What we saw in your data',
      facts: 'All facts',
      institution: 'Institution',
      place: 'Location',
      fields: 'Fields',
      mode: 'Study mode',
      modes: { 'full-time': 'Full-time', 'part-time': 'Part-time', both: 'Full- or part-time', distance: 'Distance learning' } as Record<string, string>,
      sector: 'Funding',
      public: 'Public',
      private: 'Private',
      source: 'Data',
      page: 'Programme page',
      website: 'Institution website',
      search: 'Search the web',
    },
    search: 'Search programme, university, city',
    allCountries: 'All countries',
    allLevels: 'All levels',
    sort: { match: 'Best match', cost: 'Lowest tuition', earnings: 'Highest earnings', new: 'Newest' },
    count: (n: string) => `${n} programmes`,
    dataFrom: (d: string) => ` · data from ${d}`,
    updating: ' · updating …',
    prev: '← Previous',
    nextPage: 'Next →',
    researchTitle: 'More countries: where your fields are strong',
    researchSub:
      'For these countries there’s no official programme-by-programme list yet. Instead: the universities with the most research in your fields (OpenAlex), a strong sign a field is taught seriously, plus every university in the country.',
    universities: (n: number) => `${n} universities`,
    typical: 'Typical tuition',
    noResearch: 'No research profile data for your fields here.',
    ranked: (n: number) => `${n} universities ranked · unlock to see them`,
    allUnis: (n: number) => `All ${n} universities`,
    searchProgrammes: 'search programmes',
    checkoutFailed: 'Checkout failed.',
  },
  fields: {
    title: 'Fields of study',
    sub: (n: number) => `The ${n} fields we match you to. Not sure which is yours?`,
    findOut: 'Find out',
    tracked: (n: string) => `${n} programmes tracked`,
    back: 'All fields',
    whoTitle: 'Who it suits',
    traits: (t: string) => `Students here tend to be a bit more ${t} than average.`,
    buildsOn: 'Builds on',
    offers: 'Typically offers',
    leadsTo: 'Where it leads',
    related: 'Related fields',
    ctaTitle: (f: string) => `Is ${f} right for you?`,
    ctaText: 'Find out from what you actually watch, read and build, plus a five-minute questionnaire. Free, in your browser.',
    cta: 'Find my field',
    metaTitle: (f: string) => `Should I study ${f}?`,
    whereLocal: (f: string) => `Where to study ${f}`,
    whereLocalSub: 'Universities that teach this field, from official statistics.',
  },
  trust: {
    openSource: 'Open source',
    nothingStored: 'We store nothing',
    viewCode: 'See the code on GitHub',
    startNote: 'Your data is read here in your browser and none of it reaches us. To look up programmes we only send the names of your fields, and we don’t keep those either. The site is open source, so anyone can check.',
    point: 'Open source: every line of code is public',
    footer: 'Open source (MIT) on GitHub',
  },
  share: {
    title: 'Share or keep your result',
    sub: 'Your whole result is in the link, nothing is stored. No videos, searches or names go in, only fields, percentages and your profile.',
    copy: '🔗 Copy link',
    copied: '✓ Copied',
    copyFallback: 'Copy this link:',
    share: '↗ Share',
    mail: '✉ Email it to me',
    mailSubject: (name: string) => `My result on ${name}`,
    mailBody: (url: string) => `Here is my result:\n${url}\n\nThe link holds the whole result. Nothing is stored anywhere.`,
    banner: (date: string) => `A shared result from ${date}: fields, percentages and profile, no personal data.`,
    own: 'Get your own result →',
    lockedText: 'Place 1 is part of the full report. Make your own to see yours.',
    broken: 'This link is incomplete or broken.',
  },
  sourceInsights: {
    title: 'What your data says about you',
    sub: 'Each source on its own: which fields it backs, which topics it holds, when you’re active.',
    points: (n: string, span?: string) => `${n} data points${span ? `, ${span}` : ''}`,
    fields: 'Stands out',
    share: (pct: number) => (pct < 1 ? 'under 1% of this source' : `${pct}% of this source`),
    topics: 'Most frequent topics',
    examples: 'For example',
    learning: (pct: number) => `${pct}% looks like learning rather than entertainment`,
    hours: (from: number, to: number) => `Most active between ${from}:00 and ${to}:00`,
    nothing: 'Nothing here stands out against what everyone does.',
    locked: 'In the full report: what each of your sources says on its own.',
    teaser: (fields: number, topics: number) => `${fields} field${fields === 1 ? '' : 's'} stand${fields === 1 ? 's' : ''} out · ${topics} topics`,
  },
  studyInfo: {
    title: (n: string) => `${n} items about choosing a degree don’t count`,
    text: (fields: string) =>
      `Videos, searches and pages like “Should you study psychology?” or “sociology master zurich” are about the decision, not the subject. So they don’t count as interest.${fields ? ` Most were about ${fields}.` : ''}`,
    examples: 'Examples we left out',
    stale: 'Part of your data was read by an older version. Since then we spot degree research in every source and match your topics to single programmes. Upload the files again (or reconnect) for that to apply.',
    staleCta: 'Upload again',
  },
  contrib: {
    title: 'Where this comes from',
    parts: {
      riasec: 'Questionnaire: interest type',
      riasecData: 'Interest type from your data',
      subjects: 'Questionnaire: school subjects',
      values: 'Questionnaire: what matters to you',
      personality: 'Questionnaire: personality',
      footprint: 'Baseline, no direct hits',
    },
    pct: (n: number) => `${n}%`,
  },
  earnings: {
    ch: 'Median salary in Switzerland, one year after graduating',
    chShort: 'Median salary in Switzerland',
    uhMaster: 'University master’s',
    fhBachelor: 'UAS bachelor’s',
    teaching: 'Teaching diploma',
    chSource: (year?: string) => `Swiss Federal Statistical Office, graduate survey${year ? `, class of ${year}` : ''}, gross, full-time`,
    us: 'US median earnings, one year after a bachelor’s',
    usSource: 'College Scorecard, US Department of Education',
  },
  sourceNames: {
    youtube: 'YouTube subscriptions & likes', takeout: 'YouTube watch history', 'google-search': 'Google activity', spotify: 'Spotify', 'spotify-export': 'Spotify (file)', instagram: 'Instagram', tiktok: 'TikTok', reddit: 'Reddit', github: 'GitHub', questionnaire: 'Questionnaire',
  } as Record<string, string>,
  stats: {
    subscriptions: 'subscriptions', likedVideos: 'liked videos', musicLikes: 'music likes', playlists: 'playlists', playlistItems: 'playlist items', uploads: 'uploads',
    watchedVideos: 'watched videos', musicPlays: 'music plays', youtubeSearches: 'YouTube searches', googleSearches: 'Google searches', comments: 'comments', channels: 'channels',
    plays: 'plays', podcastEpisodes: 'podcast episodes', artists: 'artists', repositories: 'repositories', ownRepositories: 'own repos', starred: 'starred', topLanguage: 'top language',
    communities: 'communities', saved: 'saved', upvoted: 'upvoted', posts: 'posts', topArtists: 'top artists', followedArtists: 'followed artists', topTracks: 'top tracks',
    recentPlays: 'recent plays', savedPodcasts: 'saved podcasts', savedEpisodes: 'saved episodes', audiobooks: 'audiobooks',
    pagesVisited: 'pages visited', mapsSearches: 'Maps searches', apps: 'apps', books: 'books', articles: 'articles',
    topics: 'topics', following: 'accounts followed', likes: 'likes', savedPosts: 'saved posts', searches: 'searches', profileSearches: 'profile searches', seen: 'posts seen', entries: 'entries',
  } as Record<string, string>,
  /** Progress and error messages from the connectors, which are written in English. */
  tr: (s: string): string => s,
  meta: {
    title: 'whatshouldistudy: find your field from what you actually watch, read and build',
    description:
      'whatshouldistudy reads thousands of signals from your YouTube, Spotify, Reddit and GitHub, adds a 5-minute questionnaire built on established models, and matches you to fields of study and real programmes in the US, UK, Europe and worldwide. Your data never leaves your browser.',
    keywords: ['what should I study', 'which degree is right for me', 'college major quiz', 'study programme finder', 'university course finder', 'career test', 'RIASEC', 'Big Five', 'study abroad'],
    start: 'Find your field',
    startDesc: 'Connect YouTube, Google Takeout, Spotify, Reddit or GitHub and answer a short questionnaire. Everything runs in your browser.',
    results: 'Your result',
    fields: 'All fields of study',
    fieldsDesc: (n: number) => `${n} fields of study explained: what you learn, who they suit, where they lead, and how many programmes we track worldwide.`,
    fieldDesc: (name: string, blurb: string) => `${blurb} Who ${name} suits, which school subjects it draws on, where it leads, and programmes worldwide.`,
    how: 'How it works',
    howDesc: 'The model behind whatshouldistudy: what we read from each source, how interest is measured, the psychology we use, and where the programme data comes from.',
    privacy: 'Privacy',
    terms: 'Terms',
    connecting: 'Connecting …',
    unlocked: 'Unlocked',
    imprint: 'Imprint',
  },
  misc: {
    start: 'Start',
    home: (n: string) => `${n} home`,
    couldNotUnlock: 'Could not unlock.',
    profileLabel: 'Interest profile',
    menu: 'Menu',
    madeIn: 'Made in Zürich',
    dataCredit: 'Programme data: College Scorecard, Discover Uni, Parcoursup, BFS, OpenAlex',
  },
  callback: {
    reading: (s: string) => `Reading your ${s}`,
    failed: (s: string) => `Couldn’t read ${s}`,
    finishing: 'Finishing sign-in',
    local: 'This happens in your browser. Nothing is uploaded to us.',
    back: 'Back',
    unknown: 'Unknown provider.',
    generic: 'Something went wrong.',
  },
  unlocked: {
    working: 'Unlocking your full report …',
    failed: 'Something went wrong',
    charged: 'If you were charged, reply to your Stripe receipt and we’ll sort it out.',
  },
}

export type Dict = typeof en

const DE_MESSAGES: Array<[RegExp, string]> = [
  [/^Unpacking (.+)$/, 'Entpacke $1'],
  [/^Reading your profile$/, 'Lese dein Profil'],
  [/^Reading your repositories$/, 'Lese deine Repos'],
  [/^Reading your stars$/, 'Lese deine Sterne'],
  [/^Analysing$/, 'Werte aus'],
  [/^Reading your communities$/, 'Lese deine Communities'],
  [/^Reading saved and upvoted posts$/, 'Lese gespeicherte und upgevotete Posts'],
  [/^Reading your posts and comments$/, 'Lese deine Posts und Kommentare'],
  [/^Reading your top artists$/, 'Lese deine Top-Artists'],
  [/^Reading artists you follow$/, 'Lese Artists, denen du folgst'],
  [/^Reading your top tracks$/, 'Lese deine Top-Songs'],
  [/^Reading your podcasts$/, 'Lese deine Podcasts'],
  [/^Reading your audiobooks$/, 'Lese deine Hörbücher'],
  [/^Reading channel details$/, 'Lese Kanal-Infos'],
  [/^Reading video details$/, 'Lese Video-Infos'],
  [/^Reading your subscriptions$/, 'Lese deine Abos'],
  [/^Reading your liked videos$/, 'Lese deine gelikten Videos'],
  [/^Reading your playlists$/, 'Lese deine Playlists'],
  [/^Reading (.+)$/, 'Lese $1'],
  [/^You declined access\.$/, 'Du hast den Zugriff abgelehnt.'],
  [/^Sign-in could not be verified\. Please try again\.$/, 'Die Anmeldung liess sich nicht prüfen. Bitte nochmals versuchen.'],
  [/^That does not look like a GitHub username\.$/, 'Das sieht nicht nach einem GitHub-Username aus.'],
  [/^GitHub user "(.+)" not found\.$/, 'GitHub-User «$1» gibt es nicht.'],
  [/^GitHub rate limit reached.*$/, 'GitHub-Limit für dein Netzwerk erreicht. Versuch es in einer Stunde nochmals.'],
  [/^Spotify did not return genres.*$/, 'Spotify hat keine Genres geliefert, der Musikgeschmack fehlt deshalb.'],
  [/^YouTube quota reached.*$/, 'YouTube-Kontingent erreicht, ein Teil der Details fehlt.'],
  [/^Some playlists could not be read\.$/, 'Einige Playlists liessen sich nicht lesen.'],
  [/^(.+): Spotify streaming history$/, '$1: Spotify-Streamingverlauf'],
  [/^(.+): Spotify listening history$/, '$1: Spotify-Hörverlauf'],
  [/^(.+): ([\d,]+) activity entries$/, '$1: $2 Aktivitäten'],
  [/^(.+): (\d+) subscriptions$/, '$1: $2 Abos'],
  [/^(.+): (\d+) comments you wrote$/, '$1: $2 eigene Kommentare'],
  [/ watched videos/g, ' geschaute Videos'],
  [/ YouTube searches/g, ' YouTube-Suchen'],
  [/ Google searches/g, ' Google-Suchen'],
  [/ other activity entries/g, ' weitere Aktivitäten'],
  [/ accounts you follow/g, ' gefolgte Konten'],
  [/ posts and videos seen/g, ' gesehene Posts und Videos'],
  [/ saved posts/g, ' gespeicherte Posts'],
  [/ profile searches/g, ' Profilsuchen'],
  [/ searches/g, ' Suchen'],
  [/ topics/g, ' Themen'],
  [/ likes/g, ' Likes'],
  [/ comments/g, ' Kommentare'],
  [/ videos watched/g, ' geschaute Videos'],
  [/ entries/g, ' Einträge'],
]

const deCH: Dict = {
  nav: { how: 'So funktioniert’s', fields: 'Fächer', start: 'Los geht’s' },
  footer: {
    about: 'Dein digitaler Fussabdruck plus ein kurzer Fragebogen nach bewährten Interessen- und Persönlichkeitsmodellen. Daraus: Studienfächer und echte Studiengänge, die passen.',
    allFields: 'Alle Studienfächer',
    sources: 'Woher die Studiengänge kommen',
    privacy: 'Datenschutz',
    terms: 'AGB',
    local: 'Die Analyse läuft in deinem Browser. Wir sehen deinen Verlauf nie.',
    otherSites: 'Auch für',
    siteNames: { global: 'International', ch: 'Schweiz', de: 'Deutschland', at: 'Österreich' },
    imprint: 'Impressum',
  },
  landing: {
    badge: 'Gratis · ohne Konto · läuft in deinem Browser',
    h1a: 'Was soll ich studieren?',
    h1b: 'Frag die',
    h1c: '10’000 Entscheidungen,',
    h1d: 'die du schon getroffen hast.',
    lead: (n: number) =>
      `Du lädst deinen YouTube- und Google-Verlauf hier rein, deinen Instagram- oder TikTok-Export, wenn du willst auch Reddit und GitHub. Dein Browser liest das direkt auf deinem Gerät und zählt, zu welchen Themen du immer wieder zurückkommst. Dazu ein kurzer Fragebogen zu Interessen, Schulfächern und Werten. Heraus kommen deine Fächer aus ${n} Studienfeldern und die passenden Studiengänge an Uni, ETH, FH und PH. Gespeichert wird nichts.`,
    cta: 'Mein Fach finden',
    cta2: 'So funktioniert’s',
    totals: (p: string, i: string) => `${p} Studiengänge an ${i} Hochschulen, jede Woche aktualisiert.`,
    marquee: 'Fächer zum Entdecken',
    cols: [
      ['Dein Verlauf zeigt,', 'wofür du deine Zeit wirklich brauchst, Monat für Monat. Drei Jahre YouTube lassen sich nicht schönreden.'],
      ['Quizze fragen,', 'was dir angeblich gefällt. Die Antwort hängt davon ab, was gut klingt und wie du dich an dem Tag fühlst.'],
      ['Wir nehmen beides,', 'weil dein Verlauf deine Noten nicht kennt. Und der Fragebogen nicht weiss, dass du nachts Doku über Vulkane schaust.'],
    ],
    sourcesTitle: 'Verbinde, was du willst. Den Rest lässt du weg.',
    sourcesSub: 'Jede Quelle ist freiwillig und nur lesend. Je mehr, desto genauer.',
    sources: [
      { name: 'YouTube & Google', how: 'Einmal bei Google anfordern, eine Datei', what: 'Jedes Video, das du geschaut hast, oft über Jahre, dazu deine Google-Suchen, besuchte Seiten, Maps und Apps. Mit Abstand die beste Quelle.', n: '5’000–100’000 Signale', color: 'pink' },
      { name: 'Spotify', how: 'Bei Spotify anfordern, Datei reinziehen', what: 'Podcasts, gespeicherte Folgen und Hörbücher zeigen, was du verstehen willst. Musik gibt einen leisen Hinweis auf deine Persönlichkeit.', n: '200–20’000 Signale', color: 'lime' },
      { name: 'Instagram & TikTok', how: 'Bei Instagram oder TikTok anfordern, Datei reinziehen', what: 'Die Themen, unter denen dich Instagram führt, wem du folgst, was du likest, speicherst und suchst, deine Hashtags.', n: '300–20’000 Signale', color: 'yellow' },
      { name: 'Reddit', how: 'Anmelden, nur lesen', what: 'Die Communities, in denen du bist, was du speicherst und upvotest, was du selbst postest.', n: '100–3’000 Signale', color: 'orange' },
      { name: 'GitHub', how: 'Nur dein Username', what: 'Was du baust und was du sternst. Für Leute, die Dinge machen, das stärkste Signal überhaupt.', n: '20–600 Signale', color: 'sky' },
      { name: 'Fragebogen', how: '5 Minuten, alles freiwillig', what: 'Interessen nach Holland (RIASEC), die 20 Fragen des Mini-IPIP (Big Five), deine Schulfächer und was du vom Job willst.', n: '60 Antworten', color: 'violet' },
    ],
    privacyTitle: 'Deine Daten bleiben deine.',
    privacyBody:
      'Die Analyse läuft in deinem Browser. Anmeldungen sind nur lesend, die Schlüssel landen nie auf unserem Server. Dateien, die du reinziehst, werden auf deinem Gerät entpackt. Übrig bleibt eine Zusammenfassung in deinem Browser, mit einem Klick gelöscht. Für die Studiengänge schicken wir nur deine Top-Fächer und Filter.',
    privacyPoints: ['Wir speichern nichts: keine Datenbank, kein Konto, keine E-Mail', 'Keine Tracking-Cookies', 'Nur Lesezugriff, jederzeit widerrufbar', 'Der Rohverlauf wird nach der Analyse verworfen', 'Jeder Schritt des Modells ist offengelegt'],
    priceTitle: 'Resultat gratis. Den vollen Report, wenn du so weit bist.',
    free: 'Gratis',
    freeList: ['Deine Fächer ab Platz 2, mit den Belegen dazu', 'Versteckte Treffer, an die du nie gedacht hättest', 'Interessenprofil (RIASEC) und Big Five', 'Wie sich deine Interessen über die Jahre verschoben haben', 'Wie viele Studiengänge passen, und wo'],
    full: 'Voller Report',
    oneTime: 'einmalig · 12 Monate',
    fullList: ['Dein Platz 1, mit allen Belegen', 'Jeder passende Studiengang, für dich sortiert', 'Studiengebühren und Zulassung (Matura, BM, Passerelle)', 'Uni, ETH, FH und PH im Vergleich', 'Auch Ausland: Frankreich, UK, USA und 60 weitere Länder', 'Filter, Suche, CSV-Export, neue Studiengänge markiert'],
    faqTitle: 'Fragen',
    faq: [
      ['Speichert ihr meinen YouTube-Verlauf?', 'Nein. Die Analyse läuft in deinem Browser. Dein Verlauf geht direkt von Google auf dein Gerät, wird zu einer Zusammenfassung verdichtet, und die Rohdaten fliegen raus. Unser Server sieht sie nie.'],
      ['Ist das ein richtiger psychologischer Test?', 'Der Fragebogen nutzt etablierte Instrumente: das RIASEC-Modell von Holland, auf dem die meiste Berufs- und Studienberatung aufbaut, und den Mini-IPIP, eine geprüfte Big-Five-Skala mit 20 Fragen. Die Analyse deines Verlaufs ist unser eigenes Modell. Auf «So funktioniert’s» steht jeder Schritt, auch was es nicht kann.'],
      ['Welche Hochschulen sind drin?', 'Alle akkreditierten Schweizer Hochschulen: die zehn kantonalen Universitäten, ETH und EPFL, die Fachhochschulen und die Pädagogischen Hochschulen. Grundlage sind die Zahlen des Bundesamts für Statistik. Fürs Ausland kommen Frankreich, UK und die USA Studiengang für Studiengang dazu, für 60 weitere Länder die forschungsstärksten Unis.'],
      ['Was bringt der volle Report?', 'Deinen Platz 1 mit allen Belegen und jeden passenden Studiengang mit Gebühren, Zulassung und Link, sortiert nach deinem Profil. Einmal bezahlen, 12 Monate gültig, die Daten werden wöchentlich aktualisiert.'],
      ['Geht das auch ohne Verbindungen?', 'Ja. Der Fragebogen allein gibt schon ein brauchbares Resultat. Jede Quelle macht es genauer, und das Vertrauens-Badge beim Resultat zeigt, worauf es beruht.'],
    ],
    finalCta: 'Jetzt starten, gratis',
    next: 'Als Nächstes vom gleichen Team: welcher Job passt zu mir.',
    example: 'Beispiel-Resultat',
    exampleSignals: '14’382 Signale · 4 Quellen',
    code: 'Interessen-Code',
    codeSub: 'Macher · Denker · Organisator',
    exampleRows: [
      ['aerospace-engineering', 97, 'Everyday Astronaut, Scott Manley · 214 Videos über 31 Monate'],
      ['mechanical-engineering', 94, 'Stuff Made Here, r/CNC · deine 3 Repos'],
      ['physics', 88, 'PBS Space Time · 2 Podcasts'],
    ],
    hiddenLabel: 'Versteckter Treffer:',
    hiddenText: 'Industriedesign. Schaust du kaum, passt aber zu deinem Profil.',
    typesTitle: 'Uni, ETH, FH oder PH?',
    typesSub: 'Vier Wege an eine Hochschule, mit eigenen Zulassungsregeln. Dein Resultat zeigt, welcher zu dir passt.',
    typesCount: (n: number) => `${n} Hochschulen`,
  },
  start: {
    title: 'Los, wir finden dein Fach.',
    lead: 'Verbinde so viele Quellen, wie du magst, beantworte so viel vom Fragebogen, wie du willst, und schau dir dann dein Resultat an. Du kannst jederzeit zurückkommen und mehr ergänzen.',
    step1: 'Quellen verbinden',
    step1sub: 'Nur lesend. Die Analyse läuft in deinem Browser, nichts wird hochgeladen.',
    step2: 'Fünf Minuten über dich',
    step2sub: 'Was kein Verlauf zeigt: wie du dich selbst siehst, deine Schulfächer, was dir wichtig ist. Alles freiwillig.',
    step3: 'Wohin und was',
    step3sub: 'Damit filtern wir die Studiengänge und zeigen die Gebühren, die für dich gelten.',
    yt: 'Dein Wiedergabeverlauf, jedes Video oft über Jahre, dazu was Google sonst festhält: deine Suchen, besuchte Seiten, Maps und Apps. Die beste Quelle.',
    ytLogin: 'Oder anmelden, dann nur Abos und Likes, ohne Verlauf:',
    spotify: 'Podcasts, gespeicherte Folgen und Hörbücher, dazu deine Top-Artists für den Musikgeschmack.',
    reddit: 'Deine Communities, gespeicherte und upgevotete Posts, und was du selbst schreibst.',
    github: 'Was du baust und was du sternst. Öffentliche Daten, nur dein Username.',
    instagram: 'Die Themen, unter denen dich Instagram führt, wem du folgst, deine Likes, Gespeichertes und Suchen.',
    tiktok: 'Deine Suchen, wem du folgst, deine Hashtags und Kommentare.',
    best: 'Top',
    signalsRead: (n: string) => `${n} Signale gelesen`,
    remove: 'Entfernen',
    refresh: 'Aktualisieren',
    connect: (s: string) => `${s} verbinden`,
    notConfigured: (s: string) => `Die ${s}-Anmeldung ist hier noch nicht eingerichtet.`,
    request: {
      instagram: 'Instagram-Daten anfordern',
      tiktok: 'TikTok-Daten anfordern',
      spotify: 'Spotify-Daten anfordern',
      youtube: 'Verlauf bei Google anfordern',
    },
    hint: {
      instagram: '«Auf Gerät herunterladen» und «Gesamter Zeitraum» wählen. Nach ein paar Minuten kommt ein E-Mail mit dem Download.',
      tiktok: '«Alle Daten» wählen und anfordern. TikTok meldet sich, sobald der Download bereit ist.',
      spotify: 'Deine «Kontodaten» anfordern. Spotify schickt den Download per E-Mail, das dauert ein paar Tage.',
      takeout: [
        '«Meine Aktivitäten» ist schon angekreuzt: YouTube-Verlauf und -Suchen, Google-Suchen, Maps und Apps.',
        'Weiter unten auch «YouTube und YouTube Music» ankreuzen. Das bringt Abos, Kommentare und Playlists dazu.',
        '!Wichtig: Bei YouTube auf «Alle YouTube-Daten …» klicken und «Videos» abwählen. Das sind Videos, die du selbst hochgeladen hast. Wir brauchen sie nicht, und Google lässt uns das nicht für dich abwählen.',
        '«Nächster Schritt», dann «Export erstellen».',
        'Nach etwa 3 Minuten kommt ein E-Mail: öffnen, ganz nach unten scrollen und «Download» drücken. Diese Datei hier reinziehen.',
      ],
    },
    drop: 'Wenn das E-Mail da ist: Datei hier reinziehen',
    addAnother: 'Weitere Datei hinzufügen oder ersetzen',
    takeoutPartMissing: (files: string) => `Das ist nur das Inhaltsverzeichnis von Google: Es listet ${files} Dateien auf, enthält aber keine davon. Öffne takeout.google.com/manage (oder den Link im E-Mail von Google), scroll ganz nach unten und drück auf «Download». Die Datei, die dann kommt (oft …-1-001.zip, viel grösser), hier reinziehen.`,
    unread: (n: number, files: string) => `(${n} ${n === 1 ? 'Datei' : 'Dateien'}, die wir nicht lesen konnten: ${files})`,
    emptyTakeout: (products: string) => `In diesem Google-Archiv ist kein Verlauf${products ? ` (nur: ${products})` : ''}. Fordere es über den Button oben nochmals an, mit «Meine Aktivitäten» angekreuzt.`,
    optional: 'optional',
    spotifySlow: 'Spotify braucht ein paar Tage dafür. Podcasts und Hörbücher helfen beim Resultat, Musik nur wenig.',
    fileReady: 'Datei schon da? Hier reinziehen',
    dropSub: 'oder klicken · bleibt auf deinem Gerät',
    noHistory: 'In diesen Dateien war nichts Brauchbares. Der Button oben führt dich zur richtigen Datei.',
    githubPlaceholder: 'dein-username',
    add: 'Hinzufügen',
    localOnly: 'Alles hier ist nur in diesem Browser gespeichert.',
    deleteAll: 'Alle meine Daten löschen',
    deleteConfirm: 'Alle verbundenen Daten, Antworten und Einstellungen aus diesem Browser löschen?',
    signals: 'Signale',
    answers: 'Antworten',
    seeResult: 'Mein Resultat →',
    needMore: 'Eine Quelle verbinden oder 18 Fragen beantworten',
  },
  q: {
    tabs: { interests: 'Interessen', personality: 'Persönlichkeit', subjects: 'Schulfächer', values: 'Was dir wichtig ist' },
    hints: {
      interests: 'Wie gern würdest du …',
      personality: 'Wie gut beschreibt dich das? «Ich …»',
      subjects: 'Wie gern hast du das Fach, und wie gut bist du darin?',
      values: 'Wie wichtig ist dir das in deinem künftigen Job?',
    },
    next: (t: string) => `Weiter: ${t} →`,
    ipipNote: 'Mini-IPIP (Donnellan et al., 2006), frei verfügbare Fragen aus dem International Personality Item Pool, eigene Übersetzung.',
    likertInterest: ['Gar nicht', 'Eher nicht', 'Neutral', 'Gern', 'Sehr gern'],
    likertAccuracy: ['Stimmt gar nicht', 'Stimmt eher nicht', 'Teils, teils', 'Stimmt eher', 'Stimmt genau'],
    enjoy: 'Gern',
    goodAt: 'Gut',
    enjoyHead: 'Gern (1 = gar nicht)',
    goodHead: 'Gut darin (1 = schwach)',
    enjoyScale: ['Gar nicht', 'Wenig', 'Mittel', 'Gern', 'Sehr gern'],
    goodScale: ['Schwach', 'Unter dem Schnitt', 'Durchschnitt', 'Gut', 'Sehr gut'],
    valueScale: ['Unwichtig', 'Eher unwichtig', 'Mittel', 'Wichtig', 'Sehr wichtig'],
    riasec: {
      r1: 'Mit den Händen etwas bauen, reparieren oder auseinandernehmen',
      r2: 'Mit Maschinen, Werkzeugen oder Fahrzeugen arbeiten',
      r3: 'Deinen Arbeitstag draussen oder in einer Werkstatt verbringen',
      i1: 'Herausfinden, warum etwas in der Natur so funktioniert, wie es funktioniert',
      i2: 'Ein schwieriges Mathe-, Logik- oder Programmierproblem lösen',
      i3: 'Ein Experiment durchführen und die Resultate auswerten',
      a1: 'Eine Geschichte, einen Song, ein Drehbuch oder einen Artikel schreiben',
      a2: 'Etwas gestalten, das gut aussieht: ein Plakat, eine App, einen Raum',
      a3: 'Auftreten: Musik, Theater, Tanz oder Videos machen',
      s1: 'Jemandem etwas beibringen oder erklären',
      s2: 'Jemandem durch eine schwierige Zeit helfen',
      s3: 'Dich um die Gesundheit oder das Wohl anderer kümmern',
      e1: 'Eine Gruppe von deiner Idee überzeugen',
      e2: 'Ein eigenes Projekt oder Business starten und führen',
      e3: 'Ein Team führen und für das Resultat geradestehen',
      c1: 'Informationen so ordnen, dass alles stimmt',
      c2: 'Den Überblick über Geld, Budgets oder Zahlen behalten',
      c3: 'Einem klaren Ablauf folgen, um ein präzises Resultat zu bekommen',
    },
    big5: {
      b1: 'Bin der Mittelpunkt jeder Party.',
      b2: 'Fühle mit, wenn es anderen schlecht geht.',
      b3: 'Erledige Aufgaben sofort.',
      b4: 'Habe häufig Stimmungsschwankungen.',
      b5: 'Habe eine lebhafte Fantasie.',
      b6: 'Rede nicht viel.',
      b7: 'Interessiere mich nicht für die Probleme anderer.',
      b8: 'Vergesse oft, Dinge an ihren Platz zurückzulegen.',
      b9: 'Bin die meiste Zeit entspannt.',
      b10: 'Interessiere mich nicht für abstrakte Ideen.',
      b11: 'Rede an Partys mit vielen verschiedenen Leuten.',
      b12: 'Spüre die Gefühle anderer.',
      b13: 'Mag Ordnung.',
      b14: 'Rege mich schnell auf.',
      b15: 'Habe Mühe, abstrakte Ideen zu verstehen.',
      b16: 'Halte mich im Hintergrund.',
      b17: 'Interessiere mich nicht wirklich für andere.',
      b18: 'Bringe Dinge durcheinander.',
      b19: 'Bin selten niedergeschlagen.',
      b20: 'Habe keine gute Vorstellungskraft.',
    },
  },
  prefs: {
    studying: 'Studierst du schon etwas?',
    studyingHint: 'Dann zählt, was du seither dafür suchst und schaust, kaum noch. Das ist Studienstoff, kein Interesse.',
    notStudying: 'Nein',
    since: 'Seit',
    sinceUnknown: 'Seit … (weiss nicht)',
    sinceYear: (y: number) => `seit ${y}`,
    level: 'Stufe',
    levels: { bachelor: 'Bachelor', master: 'Master', any: 'Beides' },
    origin: 'Dein Abschluss / deine Herkunft',
    originHint: 'Entscheidet, welche Gebühren für dich gelten.',
    origins: { eu: 'EU / EWR', ch: 'Schweiz', uk: 'Grossbritannien', us: 'USA', other: 'Anderes Land' },
    maxFee: 'Maximale Studiengebühr pro Jahr',
    noLimit: 'Egal',
    english: 'Nur Studiengänge auf Englisch',
    where: 'Wo willst du studieren?',
    anywhere: 'Überall',
    clear: (n: number) => `Zurücksetzen (${n})`,
    regions: { us: 'USA', uk: 'Grossbritannien', eu: 'Europäische Union', dach: 'Schweiz, Deutschland, Österreich', nordics: 'Skandinavien', anglo: 'Englischsprachig' },
    withData: 'Jeder Studiengang einzeln',
    withoutData: 'Forschungsstärkste Unis + Verzeichnis',
  },
  results: {
    calculating: 'Rechne …',
    nothingTitle: 'Noch nichts zum Auswerten',
    nothingText: 'Verbinde zuerst eine Quelle oder beantworte einen Teil des Fragebogens.',
    signalsFrom: (n: string, s: string) => `${n} Signale aus ${s}`,
    yourAnswers: 'deinen Antworten',
    title: 'Dein Resultat',
    addMore: 'Mehr Daten hinzufügen',
    confidence: { low: 'Wenig Daten: Quelle oder Fragebogen ergänzen', medium: 'Solide Grundlage', high: 'Starke Grundlage' },
    confidenceTip: 'Wie viele Daten und welche Arten von Angaben hinter dem Resultat stecken',
    best: 'Passt am besten',
    lockedTitle: 'Dein Platz 1 steht fest',
    lockedText: 'Er gehört zum vollen Report, zusammen mit allen Studiengängen, die zu deinen Top-Fächern passen.',
    lockedCta: 'Platz 1 freischalten ↓',
    lockedChip: 'Platz 1',
    matchPct: (n: number) => `${n} % Match`,
    yearRank: (n: number) => `Platz ${n} in diesem Jahr`,
    relative: (n: number) => `Match im Vergleich zu allen ${n} Fächern`,
    leadsTo: 'Führt zu',
    more: 'Mehr über dieses Fach →',
    next: 'Deine nächstbesten Fächer',
    why: 'Warum?',
    less: 'Weniger',
    topics: 'Erkannte Themen',
    examples: (n: number) => `${n} Beispiele aus deinen Daten`,
    hiddenTitle: 'Versteckte Treffer',
    hiddenSub: 'Fächer, mit denen du online kaum zu tun hast, die aber zu deinen Interessen, deiner Persönlichkeit und deinen Fächern passen.',
    riasecTitle: 'Interessenprofil',
    riasecSub: (from: string, code: string) => `Die sechs RIASEC-Typen nach Holland, aus ${from}. Dein Code: ${code}`,
    from: { questionnaire: 'dem Fragebogen', footprint: 'deinem Verlauf', and: ' und ' },
    big5Title: 'Persönlichkeit',
    big5Sub: 'Big Five, verglichen mit Leuten in deinem Alter.',
    big5Q: 'Aus deinem Fragebogen.',
    big5Music: 'Nur aus deinem Musikgeschmack geschätzt. Ein schwaches Signal, nimm es locker.',
    percentile: (n: number) => `${n}. Perzentil`,
    middle: 'Im Mittelfeld',
    big5Missing: 'Beantworte die 20 Persönlichkeitsfragen (2 Minuten), damit sie mitzählt.',
    addIt: 'Ergänzen',
    insightsTitle: 'Was deine Daten sagen',
    timelineTitle: 'Wie sich deine Interessen verschoben haben',
    timelineSub: 'Deine drei stärksten Fächer pro Jahr, nach Rang, verglichen mit dem, was alle schauen.',
    timelineStudying: (field: string, since?: number) => `${field} ist ${since ? `ab ${since}` : 'hier'} ausgeblendet: Das studierst du, das ist Studienstoff.`,
    components: { interest: 'Womit du dich beschäftigst', riasec: 'Interessentyp', personality: 'Persönlichkeit', subjects: 'Schulfächer', values: 'Was dir wichtig ist' },
    kinds: {
      subscription: 'abonniert', like: 'geliked', watch: 'geschaut', search: 'gesucht', google: 'gegoogelt', comment: 'kommentiert', playlist: 'Playlist', upload: 'dein Video',
      podcast: 'Podcast', episode: 'Folge', book: 'Hörbuch', subreddit: 'Community', saved: 'gespeichert', upvote: 'upgevotet', post: 'dein Post',
      repo: 'dein Repo', fork: 'Fork', star: 'gesternt', bio: 'Bio', topic: 'Thema',
    },
  },
  reasons: {
    interest: (items: number, months: number) =>
      months > 1 ? `${items} Dinge, die du geschaut, abonniert oder gespeichert hast, drehen sich darum, verteilt über ${months} Monate.` : `${items} Dinge, die du geschaut, abonniert oder gespeichert hast, drehen sich darum.`,
    riasec: (types: string) => `Passt zu deinem Interessentyp: ${types}.`,
    subjects: (s: string) => `Baut auf ${s} auf, und das hast du gern.`,
    subjectsLow: (s: string) => `Braucht viel ${s}, und das magst du eher nicht.`,
    values: (v: string) => `Passt zu dem, was dir wichtig ist: ${v}.`,
    personality: (high: boolean, trait: string) => `Passt zu deiner ${high ? 'hohen' : 'tiefen'} ${trait.replace(/^Emotionale /, 'emotionalen ')}.`,
    hidden: 'Schaust oder liest du kaum, aber dein Profil passt.',
    studying: (since?: number) =>
      since ? `Studierst du seit ${since}. Was du seither dazu gesucht und geschaut hast, zählt kaum.` : 'Studierst du schon. Was du dazu suchst und schaust, zählt deshalb kaum.',
    and: ' und ',
  },
  insights: {
    datapoints: { title: 'Ausgewertete Signale', detail: (s: number) => `Aus ${s} ${s === 1 ? 'Quelle' : 'Quellen'}, komplett in deinem Browser.` },
    learning: {
      title: 'Lern-Anteil',
      detail: (share: number) =>
        share > 45
          ? 'Ein grosser Teil von dem, was du schaust, dreht sich ums Verstehen. Gutes Zeichen fürs Studium.'
          : share > 25
            ? 'Eine gesunde Mischung aus Lernen und Unterhaltung.'
            : 'Vor allem Unterhaltung. Deine Antworten im Fragebogen zählen deshalb mehr.',
    },
    breadth: {
      title: 'Neugier-Typ',
      value: { explorer: 'Entdecker:in', specialist: 'Spezialist:in', focused: 'Fokussiert neugierig' },
      detail: (style: string, areas: number, spread: boolean) =>
        style === 'explorer'
          ? `Du folgst ${areas} verschiedenen Fachgebieten. Schau dir interdisziplinäre Studiengänge an.`
          : style === 'specialist'
            ? 'Deine Interessen liegen in wenigen Gebieten. Ein spezialisierter Studiengang hält dich bei der Stange.'
            : `Du gehst bei wenigen Gebieten in die Tiefe und schaust insgesamt in ${areas} hinein.${spread ? ' Deine Top drei liegen in verschiedenen Bereichen. Ein Major-Minor-Studium wäre eine Überlegung wert.' : ''}`,
    },
    consistency: {
      title: 'Ausdauer',
      value: { long: 'Langfristig', recurring: 'Wiederkehrend', recent: 'Frisch' },
      detail: { long: 'Deine Top-Interessen tauchen Monat für Monat auf, nicht nur phasenweise. Ein starkes Zeichen, dass sie echt sind.', recurring: 'Deine Top-Interessen kommen regelmässig wieder.', recent: 'Deine Top-Interessen sind eher neu. Lohnt sich zu prüfen, ob sie bleiben.' },
    },
    rhythm: {
      title: 'Tagesrhythmus',
      value: { owl: 'Nachteule', early: 'Frühaufsteher:in', day: 'Tagmensch' },
      detail: (peak: number, night: number) => `Am aktivsten bist du um ${peak} Uhr${night > 20 ? `, und ${night} % passiert zwischen Mitternacht und 5 Uhr` : ''}. Nur zum Spass, es ändert nichts an deinen Fächern.`,
    },
    maker: { title: 'Macher:in', detail: (n: number) => `Du konsumierst nicht nur: ${n} Dinge hast du selbst veröffentlicht oder gebaut. Projektlastige Studiengänge, etwa an einer FH, passen zu dir.`, value: (n: number) => (n >= 10 ? 'Builder' : 'Creator') },
  },
  programmes: {
    title: 'Wo du das studieren kannst',
    sub: (where: string, level: string) => `Echte Studiengänge für deine Top-Fächer${where}, ${level}.`,
    inCountries: (n: number) => ` in ${n} Ländern`,
    inList: (names: string[]) => ` in ${names.join(', ')}`,
    anywhere: ', überall wo wir Daten haben',
    levelText: { any: 'Bachelor und Master', master: 'Master', bachelor: 'Bachelor' },
    change: 'Ändern',
    demo: 'Demo-Daten: Hier läuft ein kleiner Beispieldatensatz, bis der wöchentliche Daten-Lauf durch ist.',
    matchCount: 'Studiengänge passen zu deinen Top-Fächern und Filtern',
    freeTop: (n: number) => `Deine Top ${n}, gratis:`,
    loading: 'Suche Studiengänge …',
    boxTitle: 'Den vollen Report holen',
    boxSub: 'Dein Platz 1 und alles, was zu deinen Top-Fächern passt, für dich sortiert.',
    boxList: (n: string) => ['Dein Platz 1, mit allen Belegen', `Alle ${n} passenden Studiengänge`, 'Gebühren und Zulassung für dich', 'Uni, ETH, FH und PH im Vergleich', 'Forschungsstärkste Unis in 60 weiteren Ländern', 'Filter, Suche und CSV-Export', 'Neue Studiengänge markiert, wöchentlich aktualisiert'],
    paymentsOff: 'Bezahlen ist hier noch nicht eingerichtet.',
    unlockFree: 'Freischalten (hier gratis)',
    unlock: (p: string) => `Zahlungspflichtig bestellen · ${p}`,
    minors: 'Unter 18? Bitte nur mit Einverständnis deiner Eltern kaufen.',
    opening: 'Öffne Bezahlung …',
    boxNote: 'Einmalig · 12 Monate gültig · sichere Bezahlung über Stripe (Karte, TWINT)',
    row: { field: 'Fach', level: 'Stufe', duration: 'Dauer', yrs: 'Jahre', fee: 'Gebühr/Jahr', feeSemester: 'Gebühr/Semester', free: 'Gratis', approx: ' (ca.)', seePage: 'Siehe Website', openPage: 'Seite des Studiengangs öffnen', earnings: (y: number) => `Lohn ${y} J. danach`, debt: 'Median-Schulden', admission: 'Zulassungsquote', places: 'Plätze', students: 'Studierende', language: 'Sprache', entry: 'Zulassung', isNew: 'Neu', matchTip: 'Wie gut dieser Studiengang zu deinen Fächern passt' },
    fit: {
      why: 'Passt zu dir wegen',
      example: 'z.B. hast du angeschaut oder gesucht:',
      title: 'Warum dieser Studiengang zu dir passt',
      intro: 'Er nennt Themen, die in deinen Daten immer wieder vorkommen:',
      inData: (n: string, sources: string) => `${n}× in deinen Daten (${sources})`,
      bonus: 'Diese Themen schieben ihn in deiner Liste nach oben. Die Beispiele bleiben in deinem Browser, an unseren Server gingen fürs Sortieren nur die Themenwörter.',
    },
    details: {
      open: 'Details und warum es zu dir passt',
      close: 'Details ausblenden',
      rank: (n: number, field: string) => `${field} ist bei dir Platz ${n}.`,
      items: (items: string, months: number) =>
        months > 1 ? `${items} deiner Videos, Suchen und Beiträge drehen sich darum, über ${months} Monate verteilt.` : `${items} deiner Videos, Suchen und Beiträge drehen sich darum.`,
      named: (terms: string[]) => `Deine Themen in seinen Schwerpunkten: ${terms.map((x) => `«${x}»`).join(', ')}.`,
      forYou: 'Was davon zu dir passt',
      noOverlap: (field: string) => `Keines deiner Themen steht in der Beschreibung. Er passt über das Fach ${field} allgemein.`,
      onlyField: (field: string) => `Zu diesem Studiengang haben wir noch keine Beschreibung, er passt über das Fach ${field} allgemein. Die Seite der Hochschule nennt die Schwerpunkte.`,
      noInfo: 'Zu diesem Studiengang haben wir noch keine Beschreibung. Die Seite der Hochschule nennt die Schwerpunkte.',
      fieldGeneral: (field: string) => `${field} und du`,
      focus: 'Schwerpunkte',
      about: 'Zum Studiengang',
      also: (list: string[]) => `Deckt auch ${list.join(' und ')} ab.`,
      alsoRank: (field: string, n: number) => `${field} (bei dir Platz ${n})`,
      topics: 'Deine Themen in diesem Fach',
      seen: 'Was wir in deinen Daten gesehen haben',
      facts: 'Alle Angaben',
      institution: 'Hochschule',
      place: 'Ort',
      fields: 'Fächer',
      mode: 'Studienform',
      modes: { 'full-time': 'Vollzeit', 'part-time': 'Teilzeit', both: 'Voll- oder Teilzeit', distance: 'Fernstudium' } as Record<string, string>,
      sector: 'Träger',
      public: 'Öffentlich',
      private: 'Privat',
      source: 'Daten',
      page: 'Seite des Studiengangs',
      website: 'Website der Hochschule',
      search: 'Im Web suchen',
    },
    search: 'Studiengang, Hochschule, Ort suchen',
    allCountries: 'Alle Länder',
    allLevels: 'Alle Stufen',
    sort: { match: 'Passt am besten', cost: 'Günstigste zuerst', earnings: 'Höchster Lohn', new: 'Neueste' },
    count: (n: string) => `${n} Studiengänge`,
    dataFrom: (d: string) => ` · Daten vom ${d}`,
    updating: ' · aktualisiere …',
    prev: '← Zurück',
    nextPage: 'Weiter →',
    researchTitle: 'Weitere Länder: wo deine Fächer stark sind',
    researchSub:
      'Für diese Länder gibt es noch keine offizielle Liste Studiengang für Studiengang. Dafür: die Unis mit der meisten Forschung in deinen Fächern (OpenAlex), ein gutes Zeichen, dass das Fach dort ernsthaft gelehrt wird, plus alle Hochschulen des Landes.',
    universities: (n: number) => `${n} Hochschulen`,
    typical: 'Typische Gebühr',
    noResearch: 'Keine Forschungsdaten zu deinen Fächern hier.',
    ranked: (n: number) => `${n} Unis gerankt · freischalten zum Ansehen`,
    allUnis: (n: number) => `Alle ${n} Hochschulen`,
    searchProgrammes: 'Studiengänge suchen',
    checkoutFailed: 'Bezahlung konnte nicht starten.',
  },
  fields: {
    title: 'Studienfächer',
    sub: (n: number) => `Die ${n} Fächer, die wir dir zuordnen. Weisst du nicht, welches deins ist?`,
    findOut: 'Finde es heraus',
    tracked: (n: string) => `${n} Studiengänge in der Schweiz`,
    back: 'Alle Fächer',
    whoTitle: 'Für wen es passt',
    traits: (t: string) => `Wer das studiert, ist im Schnitt etwas ${t}.`,
    buildsOn: 'Baut auf',
    offers: 'Bietet typischerweise',
    leadsTo: 'Wohin es führt',
    related: 'Verwandte Fächer',
    ctaTitle: (f: string) => `Passt ${f} zu dir?`,
    ctaText: 'Finde es heraus, aus dem, was du wirklich schaust, liest und baust, plus fünf Minuten Fragebogen. Gratis, in deinem Browser.',
    cta: 'Mein Fach finden',
    metaTitle: (f: string) => `${f} studieren: passt das zu mir?`,
    whereLocal: (f: string) => `Wo du ${f} in der Schweiz studieren kannst`,
    whereLocalSub: 'Hochschulen mit Bachelor- oder Master-Studierenden in diesem Fach, laut Bundesamt für Statistik.',
  },
  trust: {
    openSource: 'Open Source',
    nothingStored: 'Wir speichern nichts',
    viewCode: 'Code auf GitHub ansehen',
    startNote: 'Deine Daten werden hier in deinem Browser gelesen, nichts davon kommt bei uns an. Für die Suche nach Studiengängen schicken wir nur die Namen deiner Fächer, und auch die behalten wir nicht. Die Seite ist Open Source, jede:r kann das nachprüfen.',
    point: 'Open Source: jede Zeile Code ist öffentlich',
    footer: 'Open Source (MIT) auf GitHub',
  },
  share: {
    title: 'Resultat teilen oder aufbewahren',
    sub: 'Dein ganzes Resultat steckt im Link, gespeichert wird nichts. Keine Videos, Suchen oder Namen, nur Fächer, Prozente und dein Profil.',
    copy: '🔗 Link kopieren',
    copied: '✓ Kopiert',
    copyFallback: 'Diesen Link kopieren:',
    share: '↗ Teilen',
    mail: '✉ An mich mailen',
    mailSubject: (name: string) => `Mein Resultat bei ${name}`,
    mailBody: (url: string) => `Hier ist mein Resultat:\n${url}\n\nDer Link enthält das ganze Resultat. Gespeichert wird nirgends etwas.`,
    banner: (date: string) => `Ein geteiltes Resultat vom ${date}: Fächer, Prozente und Profil, keine persönlichen Daten.`,
    own: 'Eigenes Resultat erstellen →',
    lockedText: 'Platz 1 gehört zum vollen Bericht. Mach dein eigenes Resultat, um deinen zu sehen.',
    broken: 'Dieser Link ist unvollständig oder beschädigt.',
  },
  sourceInsights: {
    title: 'Was deine Daten über dich sagen',
    sub: 'Jede Quelle für sich: welche Fächer sie stützt, welche Themen darin stecken und wann du aktiv bist.',
    points: (n: string, span?: string) => `${n} Datenpunkte${span ? `, ${span}` : ''}`,
    fields: 'Sticht heraus',
    share: (pct: number) => (pct < 1 ? 'unter 1 % dieser Quelle' : `${pct} % dieser Quelle`),
    topics: 'Häufigste Themen',
    examples: 'Zum Beispiel',
    learning: (pct: number) => `${pct} % wirkt eher nach Lernen als nach Unterhaltung`,
    hours: (from: number, to: number) => `Am aktivsten zwischen ${from} und ${to} Uhr`,
    nothing: 'Hier sticht nichts heraus gegenüber dem, was alle machen.',
    locked: 'Im vollen Bericht: was jede deiner Quellen einzeln über dich sagt.',
    teaser: (fields: number, topics: number) => `${fields} ${fields === 1 ? 'Fach sticht' : 'Fächer stechen'} heraus · ${topics} Themen`,
  },
  studyInfo: {
    title: (n: string) => `${n} Einträge über die Studienwahl zählen nicht`,
    text: (fields: string) =>
      `Videos, Suchen und Seiten wie «Psychologie studieren: lohnt sich das?» oder «soziologie uzh master» drehen sich um die Entscheidung, nicht um das Thema. Darum zählen sie nicht als Interesse.${fields ? ` Am meisten ging es um ${fields}.` : ''}`,
    examples: 'Beispiele, die wir weggelassen haben',
    stale: 'Ein Teil deiner Daten wurde mit einer älteren Version gelesen. Seither erkennen wir Studienwahl-Inhalte in allen Quellen und vergleichen deine Themen mit einzelnen Studiengängen. Lade die Dateien nochmals hoch (oder verbinde neu), damit das wirkt.',
    staleCta: 'Neu hochladen',
  },
  contrib: {
    title: 'Woher das kommt',
    parts: {
      riasec: 'Fragebogen: Interessentyp',
      riasecData: 'Interessentyp aus deinen Daten',
      subjects: 'Fragebogen: Schulfächer',
      values: 'Fragebogen: Was dir wichtig ist',
      personality: 'Fragebogen: Persönlichkeit',
      footprint: 'Grundwert, keine direkten Treffer',
    },
    pct: (n: number) => `${n} %`,
  },
  earnings: {
    ch: 'Medianlohn in der Schweiz, ein Jahr nach dem Abschluss',
    chShort: 'Medianlohn Schweiz',
    uhMaster: 'Uni-Master',
    fhBachelor: 'FH-Bachelor',
    teaching: 'PH-Lehrdiplom',
    chSource: (year?: string) => `Bundesamt für Statistik, Absolventenbefragung${year ? `, Abschlussjahrgang ${year}` : ''}, brutto, Vollzeit`,
    us: 'Medianlohn in den USA, ein Jahr nach dem Bachelor',
    usSource: 'College Scorecard, US-Bildungsministerium',
  },
  sourceNames: {
    youtube: 'YouTube-Abos & Likes', takeout: 'YouTube-Verlauf', 'google-search': 'Google-Aktivität', spotify: 'Spotify', 'spotify-export': 'Spotify (Datei)', instagram: 'Instagram', tiktok: 'TikTok', reddit: 'Reddit', github: 'GitHub', questionnaire: 'Fragebogen',
  },
  stats: {
    subscriptions: 'Abos', likedVideos: 'gelikte Videos', musicLikes: 'Musik-Likes', playlists: 'Playlists', playlistItems: 'Videos in Playlists', uploads: 'Uploads',
    watchedVideos: 'geschaute Videos', musicPlays: 'Musik-Plays', youtubeSearches: 'YouTube-Suchen', googleSearches: 'Google-Suchen', comments: 'Kommentare', channels: 'Kanäle',
    plays: 'Plays', podcastEpisodes: 'Podcast-Folgen', artists: 'Artists', repositories: 'Repos', ownRepositories: 'eigene Repos', starred: 'gesternt', topLanguage: 'Top-Sprache',
    communities: 'Communities', saved: 'gespeichert', upvoted: 'upgevotet', posts: 'Posts', topArtists: 'Top-Artists', followedArtists: 'gefolgte Artists', topTracks: 'Top-Songs',
    recentPlays: 'zuletzt gehört', savedPodcasts: 'gespeicherte Podcasts', savedEpisodes: 'gespeicherte Folgen', audiobooks: 'Hörbücher',
    pagesVisited: 'besuchte Seiten', mapsSearches: 'Maps-Suchen', apps: 'Apps', books: 'Bücher', articles: 'Artikel',
    topics: 'Themen', following: 'gefolgte Konten', likes: 'Likes', savedPosts: 'gespeicherte Posts', searches: 'Suchen', profileSearches: 'Profilsuchen', seen: 'gesehene Posts', entries: 'Einträge',
  },
  tr: (s: string): string => DE_MESSAGES.reduce((acc, [re, to]) => acc.replace(re, to), s),
  meta: {
    title: `${CH_NAME}: Welches Studium passt zu mir?`,
    description:
      'Finde dein Studienfach aus dem, was du wirklich schaust, hörst und baust: YouTube, Spotify, Reddit und GitHub plus ein kurzer Fragebogen. Dazu jeder passende Studiengang an Schweizer Unis, ETH, Fachhochschulen und PH. Deine Daten bleiben in deinem Browser.',
    keywords: ['Was soll ich studieren', 'Welches Studium passt zu mir', 'Studienwahl Test', 'Studiengänge Schweiz', 'Fachhochschule oder Uni', 'ETH Studium', 'Studienberatung', 'RIASEC', 'Big Five'],
    start: 'Finde dein Fach',
    startDesc: 'Verbinde YouTube, Google Takeout, Spotify, Reddit oder GitHub und beantworte einen kurzen Fragebogen. Alles läuft in deinem Browser.',
    results: 'Dein Resultat',
    fields: 'Alle Studienfächer',
    fieldsDesc: (n: number) => `${n} Studienfächer erklärt: was du lernst, wem sie liegen, wohin sie führen und wo du sie in der Schweiz studieren kannst.`,
    fieldDesc: (name: string, blurb: string) => `${blurb} Wem ${name} liegt, auf welchen Schulfächern es aufbaut, wohin es führt und wo du es studieren kannst.`,
    how: 'So funktioniert’s',
    howDesc: `Das Modell hinter ${CH_NAME}: was wir aus jeder Quelle lesen, wie wir Interesse messen, welche Psychologie drinsteckt und woher die Studiengänge kommen.`,
    privacy: 'Datenschutz',
    terms: 'AGB',
    connecting: 'Verbinde …',
    unlocked: 'Freigeschaltet',
    imprint: 'Impressum',
  },
  misc: {
    start: 'Los geht’s',
    home: (n: string) => `${n} Startseite`,
    couldNotUnlock: 'Freischalten hat nicht geklappt.',
    profileLabel: 'Interessenprofil',
    menu: 'Menü',
    madeIn: 'Gemacht in Zürich',
    dataCredit: 'Studiengänge: Bundesamt für Statistik (BFS), dazu Parcoursup, Discover Uni, College Scorecard, OpenAlex',
  },
  callback: {
    reading: (s: string) => `Lese dein ${s}`,
    failed: (s: string) => `${s} konnte nicht gelesen werden`,
    finishing: 'Anmeldung wird abgeschlossen',
    local: 'Das passiert in deinem Browser. Nichts wird zu uns hochgeladen.',
    back: 'Zurück',
    unknown: 'Unbekannter Anbieter.',
    generic: 'Etwas ist schiefgelaufen.',
  },
  unlocked: {
    working: 'Schalte deinen vollen Report frei …',
    failed: 'Etwas ist schiefgelaufen',
    charged: 'Falls dir etwas verrechnet wurde: Antworte auf die Stripe-Quittung, wir lösen das.',
  },
}

/** Germany: the Swiss texts in German spelling, plus what differs in substance. */
const DE_OVERRIDES: DeepPartial<Dict> = {
  landing: {
    lead: (n: number) =>
      `Du lädst deinen YouTube- und Google-Verlauf hier rein, deinen Instagram- oder TikTok-Export, wenn du willst auch Reddit und GitHub. Dein Browser liest das direkt auf deinem Gerät und zählt, zu welchen Themen du immer wieder zurückkommst. Dazu ein kurzer Fragebogen zu Interessen, Schulfächern und Werten. Heraus kommen deine Fächer aus ${n} Studienfeldern und die passenden Studiengänge an Unis, Hochschulen für angewandte Wissenschaften und dualen Hochschulen. Gespeichert wird nichts.`,
    fullList: ['Dein Platz 1, mit allen Belegen', 'Jeder passende Studiengang, für dich sortiert', 'Abschluss, Studienform und Semesterbeitrag', 'Uni, HAW und duales Studium im Vergleich', 'Auch Ausland: Österreich, Schweiz, Frankreich, UK, USA und 60 weitere Länder', 'Filter, Suche, CSV-Export, neue Studiengänge markiert'],
    faq: [
      ['Speichert ihr meinen YouTube-Verlauf?', 'Nein. Die Analyse läuft in deinem Browser. Dein Verlauf geht direkt von Google auf dein Gerät, wird zu einer Zusammenfassung verdichtet, und die Rohdaten fliegen raus. Unser Server sieht sie nie.'],
      ['Ist das ein richtiger psychologischer Test?', 'Der Fragebogen nutzt etablierte Instrumente: das RIASEC-Modell von Holland, auf dem die meiste Studien- und Berufsberatung aufbaut, und den Mini-IPIP, eine geprüfte Big-Five-Skala mit 20 Fragen. Die Analyse deines Verlaufs ist unser eigenes Modell. Auf „So funktioniert’s“ steht jeder Schritt, auch was es nicht kann.'],
      ['Welche Hochschulen sind drin?', 'Alle Studiengänge aus der Studiensuche der Bundesagentur für Arbeit: Universitäten, Hochschulen für angewandte Wissenschaften, Kunst- und Musikhochschulen, duale Hochschulen und Berufsakademien. Fürs Ausland kommen Österreich, die Schweiz, Frankreich, UK und die USA Studiengang für Studiengang dazu, für 60 weitere Länder die forschungsstärksten Unis.'],
      ['Was bringt der volle Report?', 'Deinen Platz 1 mit allen Belegen und jeden passenden Studiengang mit Abschluss, Studienform, Ort und Link, sortiert nach deinem Profil. Einmal bezahlen, 12 Monate gültig, die Daten werden wöchentlich aktualisiert.'],
      ['Geht das auch ohne Verbindungen?', 'Ja. Der Fragebogen allein gibt schon ein brauchbares Ergebnis. Jede Quelle macht es genauer, und das Vertrauens-Badge beim Ergebnis zeigt, worauf es beruht.'],
    ],
    typesTitle: 'Uni, HAW oder duales Studium?',
    typesSub: 'Drei Wege ins Studium, mit unterschiedlichen Voraussetzungen. Dein Ergebnis zeigt, welcher zu dir passt.',
    typesCount: (n: number) => `${n} Studiengänge`,
  },
  results: { title: 'Dein Ergebnis', nothingText: 'Verbinde zuerst eine Quelle oder beantworte einen Teil des Fragebogens.' },
  start: { seeResult: 'Mein Ergebnis →', lead: 'Verbinde so viele Quellen, wie du magst, beantworte so viel vom Fragebogen, wie du willst, und schau dir dann dein Ergebnis an. Du kannst jederzeit zurückkommen und mehr ergänzen.' },
  programmes: {
    boxList: (n: string) => ['Dein Platz 1, mit allen Belegen', `Alle ${n} passenden Studiengänge`, 'Abschluss, Studienform und Ort', 'Uni, HAW und duales Studium im Vergleich', 'Forschungsstärkste Unis in 60 weiteren Ländern', 'Filter, Suche und CSV-Export', 'Neue Studiengänge markiert, wöchentlich aktualisiert'],
    boxNote: 'Einmalig · 12 Monate gültig · sichere Bezahlung über Stripe',
  },
  fields: {
    tracked: (n: string) => `${n} Studiengänge in Deutschland`,
    whereLocal: (f: string) => `Wo du ${f} in Deutschland studieren kannst`,
    whereLocalSub: 'Hochschulen mit Studiengängen in diesem Fach, laut Studiensuche der Bundesagentur für Arbeit.',
  },
  meta: {
    title: `${DE_NAME}: Welches Studium passt zu mir?`,
    description:
      'Finde dein Studienfach aus dem, was du wirklich schaust, hörst und baust: YouTube, Spotify, Reddit und GitHub plus ein kurzer Fragebogen. Dazu jeder passende Studiengang an deutschen Unis und Hochschulen. Deine Daten bleiben in deinem Browser.',
    keywords: ['Was soll ich studieren', 'Welches Studium passt zu mir', 'Studienwahltest', 'Studiengänge Deutschland', 'Uni oder FH', 'Studienorientierung', 'RIASEC', 'Big Five'],
    results: 'Dein Ergebnis',
    fieldsDesc: (n: number) => `${n} Studienfächer erklärt: was du lernst, wem sie liegen, wohin sie führen und wo du sie in Deutschland studieren kannst.`,
    howDesc: `Das Modell hinter ${DE_NAME}: was wir aus jeder Quelle lesen, wie wir Interesse messen, welche Psychologie drinsteckt und woher die Studiengänge kommen.`,
  },
  misc: { dataCredit: 'Studiengänge: Studiensuche der Bundesagentur für Arbeit, dazu studienwahl.at, BFS, Parcoursup, Discover Uni, College Scorecard, OpenAlex' },
}

/** Austria: the Swiss texts in Austrian spelling, plus what differs in substance. */
const AT_OVERRIDES: DeepPartial<Dict> = {
  landing: {
    lead: (n: number) =>
      `Du lädst deinen YouTube- und Google-Verlauf hier rein, deinen Instagram- oder TikTok-Export, wenn du willst auch Reddit und GitHub. Dein Browser liest das direkt auf deinem Gerät und zählt, zu welchen Themen du immer wieder zurückkommst. Dazu ein kurzer Fragebogen zu Interessen, Schulfächern und Werten. Heraus kommen deine Fächer aus ${n} Studienfeldern und die passenden Studien an Unis, Fachhochschulen und Pädagogischen Hochschulen. Gespeichert wird nichts.`,
    fullList: ['Dein Platz 1, mit allen Belegen', 'Jedes passende Studium, für dich sortiert', 'Studienbeitrag und Aufnahmeverfahren', 'Uni, FH und PH im Vergleich', 'Auch Ausland: Deutschland, Schweiz, Frankreich, UK, USA und 60 weitere Länder', 'Filter, Suche, CSV-Export, neue Studien markiert'],
    faq: [
      ['Speichert ihr meinen YouTube-Verlauf?', 'Nein. Die Analyse läuft in deinem Browser. Dein Verlauf geht direkt von Google auf dein Gerät, wird zu einer Zusammenfassung verdichtet, und die Rohdaten fliegen raus. Unser Server sieht sie nie.'],
      ['Ist das ein richtiger psychologischer Test?', 'Der Fragebogen nutzt etablierte Instrumente: das RIASEC-Modell von Holland, auf dem die meiste Studien- und Berufsberatung aufbaut, und den Mini-IPIP, eine geprüfte Big-Five-Skala mit 20 Fragen. Die Analyse deines Verlaufs ist unser eigenes Modell. Auf „So funktioniert’s“ steht jeder Schritt, auch was es nicht kann.'],
      ['Welche Hochschulen sind drin?', 'Jedes Studium an öffentlichen Universitäten, Fachhochschulen, Pädagogischen Hochschulen und Privatuniversitäten in Österreich, laut studienwahl.at, dem Studienportal des Wissenschaftsministeriums. Fürs Ausland kommen Deutschland, die Schweiz, Frankreich, UK und die USA Studiengang für Studiengang dazu, für 60 weitere Länder die forschungsstärksten Unis.'],
      ['Was bringt der volle Report?', 'Deinen Platz 1 mit allen Belegen und jedes passende Studium mit Studienbeitrag, Aufnahmeverfahren und Link, sortiert nach deinem Profil. Einmal zahlen, 12 Monate gültig, die Daten werden wöchentlich aktualisiert.'],
      ['Geht das auch ohne Verbindungen?', 'Ja. Der Fragebogen allein gibt schon ein brauchbares Ergebnis. Jede Quelle macht es genauer, und das Vertrauens-Badge beim Ergebnis zeigt, worauf es beruht.'],
    ],
    typesTitle: 'Uni, FH oder PH?',
    typesSub: 'Drei Wege an die Hochschule, mit eigenen Aufnahmeregeln. Dein Ergebnis zeigt, welcher zu dir passt.',
  },
  results: { title: 'Dein Ergebnis', nothingText: 'Verbinde zuerst eine Quelle oder beantworte einen Teil des Fragebogens.' },
  start: { seeResult: 'Mein Ergebnis →', lead: 'Verbinde so viele Quellen, wie du magst, beantworte so viel vom Fragebogen, wie du willst, und schau dir dann dein Ergebnis an. Du kannst jederzeit zurückkommen und mehr ergänzen.' },
  programmes: {
    boxList: (n: string) => ['Dein Platz 1, mit allen Belegen', `Alle ${n} passenden Studien`, 'Studienbeitrag und Aufnahmeverfahren', 'Uni, FH und PH im Vergleich', 'Forschungsstärkste Unis in 60 weiteren Ländern', 'Filter, Suche und CSV-Export', 'Neue Studien markiert, wöchentlich aktualisiert'],
    boxNote: 'Einmalig · 12 Monate gültig · sichere Bezahlung über Stripe',
  },
  fields: {
    tracked: (n: string) => `${n} Studien in Österreich`,
    whereLocal: (f: string) => `Wo du ${f} in Österreich studieren kannst`,
    whereLocalSub: 'Hochschulen mit Studien in diesem Fach, laut studienwahl.at.',
  },
  meta: {
    title: `${AT_NAME}: Welches Studium passt zu mir?`,
    description:
      'Finde dein Studienfach aus dem, was du wirklich schaust, hörst und baust: YouTube, Spotify, Reddit und GitHub plus ein kurzer Fragebogen. Dazu jedes passende Studium an österreichischen Unis, FHs und PHs. Deine Daten bleiben in deinem Browser.',
    keywords: ['Was soll ich studieren', 'Welches Studium passt zu mir', 'Studienwahl Test', 'Studieren in Österreich', 'Uni oder FH', 'Studienberatung', 'RIASEC', 'Big Five'],
    results: 'Dein Ergebnis',
    fieldsDesc: (n: number) => `${n} Studienfächer erklärt: was du lernst, wem sie liegen, wohin sie führen und wo du sie in Österreich studieren kannst.`,
    howDesc: `Das Modell hinter ${AT_NAME}: was wir aus jeder Quelle lesen, wie wir Interesse messen, welche Psychologie drinsteckt und woher die Studien kommen.`,
  },
  misc: { dataCredit: 'Studien: studienwahl.at (BMFWF), dazu Bundesagentur für Arbeit, BFS, Parcoursup, Discover Uni, College Scorecard, OpenAlex' },
}

const deDE = mergeDeep(regionalizeDeep(deCH, 'de-DE'), regionalizeDeep(DE_OVERRIDES, 'de-DE'))
const deAT = mergeDeep(regionalizeDeep(deCH, 'de-AT'), regionalizeDeep(AT_OVERRIDES, 'de-AT'))

export const DICTS: Record<Locale, Dict> = { en, 'de-CH': deCH, 'de-DE': deDE, 'de-AT': deAT }

export function dict(locale: Locale): Dict {
  return DICTS[locale]
}
