/** French names and summaries for the study-field taxonomy. */
export const FIELDS_FR: Record<string, { name: string; blurb: string }> = {
  mathematics: { name: 'Mathématiques', blurb: 'Étudie les nombres, les structures et les preuves, des modèles abstraits à leurs applications en physique, en finance et en informatique.' },
  'statistics-data-science': { name: 'Statistiques et science des données', blurb: 'Transforme des données complexes en conclusions grâce aux probabilités, à l’analyse et à la visualisation.' },
  'computer-science': { name: 'Informatique', blurb: 'Conçois des algorithmes, des logiciels et des systèmes qui résolvent des problèmes de manière fiable.' },
  'artificial-intelligence': { name: 'Intelligence artificielle et apprentissage automatique', blurb: 'Crée des modèles, des réseaux neuronaux et des systèmes intelligents, puis étudie leurs usages responsables.' },
  cybersecurity: { name: 'Cybersécurité et réseaux', blurb: 'Protège les systèmes numériques grâce à la cryptographie, aux tests de sécurité et à l’analyse informatique.' },
  'information-systems': { name: 'Systèmes d’information', blurb: 'Relie l’informatique aux organisations : logiciels de gestion, bases de données et transformation numérique.' },
  'computer-engineering': { name: 'Informatique technique', blurb: 'Travaille à la frontière entre matériel et logiciel, des puces aux systèmes embarqués.' },
  physics: { name: 'Physique', blurb: 'Explore les lois de la nature, des particules et des matériaux aux lasers et à l’Univers.' },
  astronomy: { name: 'Astronomie et astrophysique', blurb: 'Étudie les étoiles, les galaxies et le cosmos à l’aide de télescopes, de données et de modèles.' },
  chemistry: { name: 'Chimie', blurb: 'Analyse les molécules et les réactions, crée de nouveaux composés et conçois des matériaux.' },
  biology: { name: 'Biologie', blurb: 'Étudie le vivant, des cellules et organismes à l’évolution et aux écosystèmes.' },
  'molecular-biology': { name: 'Biochimie, biologie moléculaire et biotechnologie', blurb: 'Étudie les gènes, les protéines et les cellules, ainsi que les technologies qui les modifient.' },
  neuroscience: { name: 'Neurosciences', blurb: 'Comprends comment le cerveau et le système nerveux produisent le comportement, la mémoire et les émotions.' },
  'cognitive-science': { name: 'Sciences cognitives', blurb: 'Étudie la pensée et l’intelligence sous l’angle de la psychologie, de la linguistique, de la philosophie et de l’IA.' },
  'environmental-science': { name: 'Sciences de l’environnement et écologie', blurb: 'Analyse le climat, la biodiversité et les écosystèmes, ainsi que les moyens de les préserver.' },
  'earth-sciences': { name: 'Sciences de la Terre, géologie et météorologie', blurb: 'Étudie les roches, les volcans, les océans et l’atmosphère, ainsi que l’évolution de la planète.' },
  'marine-biology': { name: 'Biologie marine et océanographie', blurb: 'Étudie la vie marine et les phénomènes physiques et chimiques des océans.' },
  zoology: { name: 'Zoologie et sciences animales', blurb: 'Étudie le comportement, la physiologie et l’évolution des animaux, ainsi que leur bien-être.' },
  geography: { name: 'Géographie', blurb: 'Analyse les territoires, les sociétés et les paysages à l’aide de cartes, de données et d’études de terrain.' },
  'mechanical-engineering': { name: 'Génie mécanique', blurb: 'Conçois des machines et des systèmes en mouvement à partir de la mécanique et de la thermodynamique.' },
  'electrical-engineering': { name: 'Génie électrique', blurb: 'Étudie les circuits, les réseaux électriques, les signaux et les télécommunications.' },
  'civil-engineering': { name: 'Génie civil', blurb: 'Conçois des ponts, des bâtiments, des tunnels et des infrastructures de transport et d’eau.' },
  'aerospace-engineering': { name: 'Génie aérospatial', blurb: 'Conçois des avions, des fusées et des satellites grâce à l’aérodynamique et aux systèmes de propulsion.' },
  'automotive-engineering': { name: 'Génie automobile', blurb: 'Développe des véhicules, des systèmes de propulsion électrique et des technologies de course.' },
  'chemical-engineering': { name: 'Génie chimique et des procédés', blurb: 'Conçois des installations et des procédés pour produire des médicaments, des matériaux et des aliments.' },
  'biomedical-engineering': { name: 'Génie biomédical', blurb: 'Développe des implants, des prothèses, des systèmes d’imagerie et des appareils médicaux.' },
  'materials-science': { name: 'Science des matériaux', blurb: 'Étudie et conçois des métaux, des polymères, des semi-conducteurs et des nanomatériaux.' },
  'robotics-mechatronics': { name: 'Robotique et mécatronique', blurb: 'Crée des machines capables de percevoir et d’agir, des robots aux systèmes automatisés.' },
  'energy-engineering': { name: 'Génie énergétique et environnemental', blurb: 'Conçois des solutions pour les énergies renouvelables, le stockage, les réseaux et l’eau.' },
  'industrial-engineering': { name: 'Génie industriel', blurb: 'Améliore les systèmes de production, la qualité, la logistique et la gestion des opérations.' },
  architecture: { name: 'Architecture et architecture d’intérieur', blurb: 'Conçois des bâtiments et des espaces agréables à vivre, fonctionnels et réalisables.' },
  'urban-planning': { name: 'Aménagement du territoire et transport', blurb: 'Planifie le logement, les transports publics, l’usage du sol et les espaces publics.' },
  'industrial-design': { name: 'Design industriel et de produits', blurb: 'Conçois des objets physiques utiles et agréables à utiliser, du mobilier aux appareils.' },
  'game-design': { name: 'Conception et développement de jeux vidéo', blurb: 'Crée des jeux en travaillant sur les mécaniques, les niveaux, les moteurs et la programmation.' },
  'ux-design': { name: 'Design UX et interaction', blurb: 'Conçois des produits numériques à partir des besoins, des interfaces et de tests avec les utilisateurs.' },
  medicine: { name: 'Médecine humaine', blurb: 'Diagnostique et traite des maladies au terme d’une formation scientifique et clinique exigeante.' },
  nursing: { name: 'Soins infirmiers et maïeutique', blurb: 'Accompagne les patients et leurs proches à l’hôpital, à domicile et dans la communauté.' },
  pharmacy: { name: 'Pharmacie et pharmacologie', blurb: 'Étudie les médicaments, leurs effets et leur développement, ainsi que leur utilisation sûre.' },
  dentistry: { name: 'Médecine dentaire', blurb: 'Préviens et traite les problèmes de santé bucco-dentaire avec précision.' },
  'veterinary-medicine': { name: 'Médecine vétérinaire', blurb: 'Soigne les animaux domestiques, les chevaux, les animaux d’élevage et la faune.' },
  physiotherapy: { name: 'Physiothérapie et réadaptation', blurb: 'Aide les personnes à retrouver leurs capacités physiques, leur mobilité et leur autonomie.' },
  'sports-science': { name: 'Sciences du sport', blurb: 'Étudie l’entraînement, la performance et la biomécanique à partir de la physiologie.' },
  nutrition: { name: 'Nutrition et sciences alimentaires', blurb: 'Étudie les effets de l’alimentation sur la santé et les procédés de production alimentaire.' },
  'public-health': { name: 'Santé publique et santé mondiale', blurb: 'Améliore la santé des populations par l’épidémiologie, la prévention et les politiques de santé.' },
  psychology: { name: 'Psychologie', blurb: 'Étudie scientifiquement la pensée, les émotions et les comportements humains.' },
  economics: { name: 'Sciences économiques', blurb: 'Analyse les marchés, les incitations et les politiques à l’aide de modèles et de données.' },
  'business-management': { name: 'Gestion d’entreprise et management', blurb: 'Organise des entreprises autour de la stratégie, du leadership, des opérations et des ressources humaines.' },
  'finance-accounting': { name: 'Finance, banque et comptabilité', blurb: 'Étudie les investissements, la finance d’entreprise, l’audit et la fiscalité.' },
  marketing: { name: 'Marketing et publicité', blurb: 'Comprends les clients et développe des marques, des campagnes et des contenus.' },
  entrepreneurship: { name: 'Entrepreneuriat et innovation', blurb: 'Lance et développe des projets en travaillant sur le produit, le financement et la croissance.' },
  logistics: { name: 'Logistique et chaîne d’approvisionnement', blurb: 'Planifie les achats, les transports et la circulation des marchandises.' },
  'hospitality-tourism': { name: 'Hôtellerie et tourisme', blurb: 'Gère des hôtels, des voyages, des événements et des destinations.' },
  'political-science': { name: 'Science politique et relations internationales', blurb: 'Étudie le pouvoir, les gouvernements, la diplomatie et les politiques publiques.' },
  law: { name: 'Droit', blurb: 'Interprète les règles et les droits dans les domaines des contrats, des tribunaux et des droits humains.' },
  criminology: { name: 'Criminologie', blurb: 'Étudie les causes de la criminalité et les réponses de la police, de la justice et de la société.' },
  sociology: { name: 'Sociologie et sciences sociales', blurb: 'Analyse les sociétés, les inégalités, les groupes et les changements culturels.' },
  anthropology: { name: 'Anthropologie et études culturelles', blurb: 'Étudie les cultures contemporaines et passées grâce aux enquêtes de terrain et à la comparaison.' },
  'social-work': { name: 'Travail social', blurb: 'Accompagne des personnes et des communautés confrontées à des situations difficiles.' },
  education: { name: 'Enseignement et pédagogie', blurb: 'Étudie l’enseignement et l’apprentissage, ou prépare-toi à concevoir des dispositifs de formation.' },
  journalism: { name: 'Journalisme', blurb: 'Trouve et raconte des faits grâce à l’enquête, au reportage et au journalisme de données.' },
  'media-communication': { name: 'Communication et médias', blurb: 'Étudie l’influence des médias et crée des stratégies de communication et des contenus.' },
  history: { name: 'Histoire', blurb: 'Reconstitue le passé à partir des sources, des empires et des conflits aux idées et à la vie quotidienne.' },
  archaeology: { name: 'Archéologie et antiquité', blurb: 'Étudie les sociétés anciennes à partir des objets, des langues et des sites archéologiques.' },
  philosophy: { name: 'Philosophie', blurb: 'Examine l’éthique, la connaissance, l’esprit, la logique et les idées d’une vie bonne.' },
  'religious-studies': { name: 'Théologie et sciences des religions', blurb: 'Étudie les religions, les textes sacrés et les traditions de manière critique.' },
  linguistics: { name: 'Linguistique', blurb: 'Analyse les sons, la grammaire, le sens et l’évolution des langues, y compris par informatique.' },
  languages: { name: 'Langues et traduction', blurb: 'Maîtrise des langues et transmets le sens entre différentes cultures.' },
  literature: { name: 'Littérature et écriture créative', blurb: 'Lis et écris avec précision, de la fiction à la poésie et à la critique.' },
  'liberal-arts': { name: 'Arts libéraux et études interdisciplinaires', blurb: 'Associe les sciences naturelles, humaines et sociales autour d’un parcours choisi.' },
  'fine-arts': { name: 'Beaux-arts et illustration', blurb: 'Pratique la peinture, le dessin, la sculpture et l’illustration.' },
  'graphic-design': { name: 'Design graphique et communication visuelle', blurb: 'Crée des identités, des mises en page et des expériences visuelles numériques.' },
  'fashion-design': { name: 'Design de mode et textile', blurb: 'Conçois des vêtements et des textiles en tenant compte de la création et de la production.' },
  'film-production': { name: 'Cinéma, télévision et vidéo', blurb: 'Réalise des films et des vidéos, de l’écriture et du tournage au montage et à la production.' },
  'animation-vfx': { name: 'Animation et effets visuels', blurb: 'Crée des animations 2D et 3D, des effets visuels et des personnages.' },
  music: { name: 'Musique, interprétation et composition', blurb: 'Interprète, compose et analyse des styles musicaux variés.' },
  'music-production': { name: 'Production musicale et ingénierie du son', blurb: 'Enregistre et mixe la musique, crée des sons et maîtrise les outils audio.' },
  'performing-arts': { name: 'Théâtre, danse et arts de la scène', blurb: 'Explore le jeu, la danse, la mise en scène et la performance.' },
  'culinary-arts': { name: 'Arts culinaires', blurb: 'Apprends la cuisine professionnelle, la pâtisserie et la gestion d’une cuisine.' },
  agriculture: { name: 'Agronomie, foresterie et horticulture', blurb: 'Produis des aliments et gère durablement les terres, les forêts et les jardins.' },
  aviation: { name: 'Aviation et formation de pilote', blurb: 'Forme-toi au pilotage et à la gestion des compagnies aériennes et des aéroports.' },
}