/** Nomi e descrizioni in italiano per la tassonomia delle aree di studio. */
export const FIELDS_IT: Record<string, { name: string; blurb: string }> = {
  mathematics: { name: 'Matematica', blurb: 'Studia numeri, strutture e dimostrazioni, dai modelli astratti alle applicazioni in fisica, finanza e informatica.' },
  'statistics-data-science': { name: 'Statistica e scienza dei dati', blurb: 'Trasforma dati complessi in conclusioni con probabilità, analisi e visualizzazione.' },
  'computer-science': { name: 'Informatica', blurb: 'Progetta algoritmi, software e sistemi che risolvono problemi in modo affidabile.' },
  'artificial-intelligence': { name: 'Intelligenza artificiale e apprendimento automatico', blurb: 'Crea modelli, reti neurali e sistemi intelligenti, studiandone anche gli usi responsabili.' },
  cybersecurity: { name: 'Sicurezza informatica e reti', blurb: 'Proteggi sistemi digitali con crittografia, test di sicurezza e analisi informatica.' },
  'information-systems': { name: 'Sistemi informativi', blurb: 'Collega informatica e organizzazioni: software gestionali, banche dati e trasformazione digitale.' },
  'computer-engineering': { name: 'Ingegneria informatica', blurb: 'Lavora al confine tra hardware e software, dai chip ai sistemi integrati.' },
  physics: { name: 'Fisica', blurb: 'Esplora le leggi della natura, dalle particelle e dai materiali ai laser e all’Universo.' },
  astronomy: { name: 'Astronomia e astrofisica', blurb: 'Studia stelle, galassie e cosmo con telescopi, dati e modelli.' },
  chemistry: { name: 'Chimica', blurb: 'Analizza molecole e reazioni, crea nuovi composti e progetta materiali.' },
  biology: { name: 'Biologia', blurb: 'Studia la vita, dalle cellule e dagli organismi all’evoluzione e agli ecosistemi.' },
  'molecular-biology': { name: 'Biochimica, biologia molecolare e biotecnologie', blurb: 'Studia geni, proteine e cellule, insieme alle tecnologie che li modificano.' },
  neuroscience: { name: 'Neuroscienze', blurb: 'Scopri come cervello e sistema nervoso generano comportamento, memoria ed emozioni.' },
  'cognitive-science': { name: 'Scienze cognitive', blurb: 'Studia pensiero e intelligenza attraverso psicologia, linguistica, filosofia e IA.' },
  'environmental-science': { name: 'Scienze ambientali ed ecologia', blurb: 'Analizza clima, biodiversità ed ecosistemi e i modi per proteggerli.' },
  'earth-sciences': { name: 'Scienze della Terra, geologia e meteorologia', blurb: 'Studia rocce, vulcani, oceani e atmosfera e i cambiamenti del pianeta.' },
  'marine-biology': { name: 'Biologia marina e oceanografia', blurb: 'Studia la vita marina e i fenomeni fisici e chimici degli oceani.' },
  zoology: { name: 'Zoologia e scienze animali', blurb: 'Studia comportamento, fisiologia ed evoluzione degli animali e il loro benessere.' },
  geography: { name: 'Geografia', blurb: 'Analizza territori, società e paesaggi con mappe, dati e ricerche sul campo.' },
  'mechanical-engineering': { name: 'Ingegneria meccanica', blurb: 'Progetta macchine e sistemi in movimento con meccanica e termodinamica.' },
  'electrical-engineering': { name: 'Ingegneria elettrica', blurb: 'Studia circuiti, reti elettriche, segnali e telecomunicazioni.' },
  'civil-engineering': { name: 'Ingegneria civile', blurb: 'Progetta ponti, edifici, gallerie e infrastrutture per trasporti e acqua.' },
  'aerospace-engineering': { name: 'Ingegneria aerospaziale', blurb: 'Progetta aerei, razzi e satelliti con aerodinamica e sistemi di propulsione.' },
  'automotive-engineering': { name: 'Ingegneria automobilistica', blurb: 'Sviluppa veicoli, propulsori elettrici e tecnologie per le competizioni.' },
  'chemical-engineering': { name: 'Ingegneria chimica e dei processi', blurb: 'Progetta impianti e processi per produrre medicinali, materiali e alimenti.' },
  'biomedical-engineering': { name: 'Ingegneria biomedica', blurb: 'Sviluppa impianti, protesi, sistemi di imaging e dispositivi medici.' },
  'materials-science': { name: 'Scienza dei materiali', blurb: 'Studia e progetta metalli, polimeri, semiconduttori e nanomateriali.' },
  'robotics-mechatronics': { name: 'Robotica e meccatronica', blurb: 'Crea macchine capaci di percepire e agire, dai robot ai sistemi automatizzati.' },
  'energy-engineering': { name: 'Ingegneria energetica e ambientale', blurb: 'Progetta soluzioni per energie rinnovabili, accumulo, reti e acqua.' },
  'industrial-engineering': { name: 'Ingegneria gestionale', blurb: 'Migliora produzione, qualità, logistica e gestione delle attività.' },
  architecture: { name: 'Architettura e architettura d’interni', blurb: 'Progetta edifici e spazi vivibili, funzionali e realizzabili.' },
  'urban-planning': { name: 'Pianificazione territoriale e trasporti', blurb: 'Pianifica abitazioni, trasporto pubblico, uso del territorio e spazi pubblici.' },
  'industrial-design': { name: 'Design industriale e di prodotto', blurb: 'Progetta oggetti fisici utili e piacevoli da usare, dai mobili ai dispositivi.' },
  'game-design': { name: 'Game design e sviluppo di videogiochi', blurb: 'Crea videogiochi lavorando su meccaniche, livelli, motori e programmazione.' },
  'ux-design': { name: 'Design UX e interazione', blurb: 'Progetta prodotti digitali partendo dai bisogni, dalle interfacce e dai test con gli utenti.' },
  medicine: { name: 'Medicina umana', blurb: 'Diagnostica e cura le malattie con una formazione scientifica e clinica approfondita.' },
  nursing: { name: 'Infermieristica e ostetricia', blurb: 'Assisti pazienti e famiglie in ospedale, a domicilio e nella comunità.' },
  pharmacy: { name: 'Farmacia e farmacologia', blurb: 'Studia i medicinali, i loro effetti, lo sviluppo e l’uso sicuro.' },
  dentistry: { name: 'Odontoiatria', blurb: 'Previeni e cura i problemi di salute orale con precisione.' },
  'veterinary-medicine': { name: 'Medicina veterinaria', blurb: 'Cura animali domestici, cavalli, animali da reddito e fauna selvatica.' },
  physiotherapy: { name: 'Fisioterapia e riabilitazione', blurb: 'Aiuta le persone a recuperare capacità fisiche, movimento e autonomia.' },
  'sports-science': { name: 'Scienze dello sport', blurb: 'Studia allenamento, prestazioni e biomeccanica attraverso la fisiologia.' },
  nutrition: { name: 'Nutrizione e scienze alimentari', blurb: 'Studia gli effetti dell’alimentazione sulla salute e la produzione di alimenti.' },
  'public-health': { name: 'Sanità pubblica e salute globale', blurb: 'Migliora la salute delle popolazioni con epidemiologia, prevenzione e politiche sanitarie.' },
  psychology: { name: 'Psicologia', blurb: 'Studia scientificamente pensieri, emozioni e comportamenti delle persone.' },
  economics: { name: 'Economia', blurb: 'Analizza mercati, incentivi e politiche con modelli e dati.' },
  'business-management': { name: 'Gestione aziendale e management', blurb: 'Organizza imprese attraverso strategia, leadership, operazioni e risorse umane.' },
  'finance-accounting': { name: 'Finanza, banche e contabilità', blurb: 'Studia investimenti, finanza aziendale, revisione e fiscalità.' },
  marketing: { name: 'Marketing e pubblicità', blurb: 'Comprendi i clienti e sviluppa marchi, campagne e contenuti.' },
  entrepreneurship: { name: 'Imprenditorialità e innovazione', blurb: 'Avvia e sviluppa progetti lavorando su prodotto, finanziamento e crescita.' },
  logistics: { name: 'Logistica e catena di approvvigionamento', blurb: 'Pianifica acquisti, trasporti e flussi di merci.' },
  'hospitality-tourism': { name: 'Ospitalità e turismo', blurb: 'Gestisci alberghi, viaggi, eventi e destinazioni.' },
  'political-science': { name: 'Scienze politiche e relazioni internazionali', blurb: 'Studia potere, governi, diplomazia e politiche pubbliche.' },
  law: { name: 'Diritto', blurb: 'Interpreta norme e diritti in ambiti come contratti, tribunali e diritti umani.' },
  criminology: { name: 'Criminologia', blurb: 'Studia le cause della criminalità e le risposte di polizia, giustizia e società.' },
  sociology: { name: 'Sociologia e scienze sociali', blurb: 'Analizza società, disuguaglianze, gruppi e cambiamenti culturali.' },
  anthropology: { name: 'Antropologia e studi culturali', blurb: 'Studia culture attuali e passate con ricerche sul campo e confronti.' },
  'social-work': { name: 'Lavoro sociale', blurb: 'Accompagna persone e comunità in situazioni difficili.' },
  education: { name: 'Insegnamento e pedagogia', blurb: 'Studia insegnamento e apprendimento o progetta percorsi formativi.' },
  journalism: { name: 'Giornalismo', blurb: 'Trova e racconta fatti attraverso inchieste, reportage e giornalismo dei dati.' },
  'media-communication': { name: 'Comunicazione e media', blurb: 'Studia l’influenza dei media e crea strategie di comunicazione e contenuti.' },
  history: { name: 'Storia', blurb: 'Ricostruisci il passato attraverso le fonti, da imperi e conflitti a idee e vita quotidiana.' },
  archaeology: { name: 'Archeologia e studi dell’antichità', blurb: 'Studia società antiche attraverso reperti, lingue e siti archeologici.' },
  philosophy: { name: 'Filosofia', blurb: 'Esamina etica, conoscenza, mente, logica e idee di una vita buona.' },
  'religious-studies': { name: 'Teologia e scienze delle religioni', blurb: 'Studia criticamente religioni, testi sacri e tradizioni.' },
  linguistics: { name: 'Linguistica', blurb: 'Analizza suoni, grammatica, significati ed evoluzione delle lingue, anche con l’informatica.' },
  languages: { name: 'Lingue e traduzione', blurb: 'Padroneggia le lingue e trasferisci significati tra culture diverse.' },
  literature: { name: 'Letteratura e scrittura creativa', blurb: 'Leggi e scrivi con precisione, dalla narrativa alla poesia e alla critica.' },
  'liberal-arts': { name: 'Arti liberali e studi interdisciplinari', blurb: 'Combina scienze naturali, umane e sociali in un percorso scelto.' },
  'fine-arts': { name: 'Belle arti e illustrazione', blurb: 'Pratica pittura, disegno, scultura e illustrazione.' },
  'graphic-design': { name: 'Design grafico e comunicazione visiva', blurb: 'Crea identità visive, impaginazioni ed esperienze digitali.' },
  'fashion-design': { name: 'Design della moda e tessile', blurb: 'Progetta abiti e tessuti considerando creatività e produzione.' },
  'film-production': { name: 'Cinema, televisione e video', blurb: 'Realizza film e video, dalla sceneggiatura alle riprese e al montaggio.' },
  'animation-vfx': { name: 'Animazione ed effetti visivi', blurb: 'Crea animazioni 2D e 3D, effetti visivi e personaggi.' },
  music: { name: 'Musica, interpretazione e composizione', blurb: 'Interpreta, compone e analizza generi musicali diversi.' },
  'music-production': { name: 'Produzione musicale e ingegneria del suono', blurb: 'Registra e mixa musica, crea suoni e lavora con tecnologie audio.' },
  'performing-arts': { name: 'Teatro, danza e arti performative', blurb: 'Esplora recitazione, danza, regia e performance.' },
  'culinary-arts': { name: 'Arti culinarie', blurb: 'Impara cucina professionale, pasticceria e gestione di una cucina.' },
  agriculture: { name: 'Agronomia, selvicoltura e orticoltura', blurb: 'Produci alimenti e gestisci in modo sostenibile terreni, boschi e giardini.' },
  aviation: { name: 'Aviazione e formazione di pilota', blurb: 'Impara a pilotare e a gestire compagnie aeree e aeroporti.' },
}