import type { Locale } from './config.ts'

const texts = {
  en: 'To understand usage, we keep monthly totals of successfully imported source types and programmes returned by our server (catalogue ID, name and institution). These counters use Upstash Redis and are deleted 90 days after the month ends. We store no individual events or links between imports and recommendations. The counters contain no file contents, filenames, history, answers, scores, access tokens, IP addresses or user identifiers. This feature sets no cookies, reads no browser storage and sends no data to advertising services. The hosting provider still processes connection data to serve requests.',
  de: 'Um die Nutzung zu verstehen, zählen wir pro Monat erfolgreich importierte Quellentypen und vom Server ausgegebene Studiengänge (Katalog-ID, Name und Hochschule). Diese Summenzähler liegen in Upstash Redis und werden 90 Tage nach Monatsende gelöscht. Wir speichern keine Einzelereignisse und verknüpfen Importe nicht mit Empfehlungen. Die Zähler enthalten keine Dateiinhalte, Dateinamen, Verläufe, Antworten, Bewertungen, Zugangstoken, IP-Adressen oder Nutzerkennungen. Diese Funktion setzt keine Cookies, liest keinen Browserspeicher und sendet keine Daten an Werbedienste. Der Hosting-Anbieter verarbeitet weiterhin Verbindungsdaten zur Bearbeitung der Anfragen.',
  fr: 'Pour comprendre l’utilisation, nous conservons des totaux mensuels des types de sources importées avec succès et des formations renvoyées par le serveur (identifiant du catalogue, nom, établissement). Ces compteurs sont stockés dans Upstash Redis et supprimés 90 jours après la fin du mois. Nous ne conservons aucun événement individuel et ne relions pas les imports aux recommandations. Aucun contenu ou nom de fichier, historique, réponse, score, jeton, adresse IP ou identifiant utilisateur ne figure dans les compteurs. Cette fonction ne dépose aucun cookie, ne lit pas le stockage du navigateur et ne transmet rien aux services publicitaires. L’hébergeur traite toujours les données de connexion nécessaires aux requêtes.',
  it: 'Per capire l’utilizzo conserviamo totali mensili dei tipi di fonti importate con successo e dei corsi restituiti dal server (identificativo del catalogo, nome, istituto). I contatori sono conservati in Upstash Redis e cancellati 90 giorni dopo la fine del mese. Non conserviamo eventi individuali e non colleghiamo importazioni e raccomandazioni. I contatori non contengono contenuti o nomi di file, cronologia, risposte, punteggi, token, indirizzi IP o identificativi utente. Questa funzione non imposta cookie, non legge la memoria del browser e non invia dati a servizi pubblicitari. Il fornitore di hosting elabora comunque i dati di connessione necessari alle richieste.',
}
export const productMeasureText = (locale: Locale) => texts[locale.startsWith('de') ? 'de' : locale.startsWith('fr') ? 'fr' : locale.startsWith('it') ? 'it' : 'en']
