/**
 * Addresses of the field pages on the German-language sites (/faecher/informatik).
 * Fixed rather than derived from the display names, so a renamed field keeps its
 * address. The English ids still work there: proxy.ts redirects them.
 */
export const FIELD_SLUG_DE: Record<string, string> = {
  mathematics: 'mathematik',
  'statistics-data-science': 'statistik-data-science',
  'computer-science': 'informatik',
  'artificial-intelligence': 'kuenstliche-intelligenz',
  cybersecurity: 'cybersecurity',
  'information-systems': 'wirtschaftsinformatik',
  'computer-engineering': 'technische-informatik',
  physics: 'physik',
  astronomy: 'astronomie',
  chemistry: 'chemie',
  biology: 'biologie',
  'molecular-biology': 'biochemie-biotechnologie',
  neuroscience: 'neurowissenschaften',
  'cognitive-science': 'kognitionswissenschaft',
  'environmental-science': 'umweltwissenschaften',
  'earth-sciences': 'erdwissenschaften',
  'marine-biology': 'meeresbiologie',
  zoology: 'zoologie',
  geography: 'geografie',
  'mechanical-engineering': 'maschinenbau',
  'electrical-engineering': 'elektrotechnik',
  'civil-engineering': 'bauingenieurwesen',
  'aerospace-engineering': 'luft-und-raumfahrttechnik',
  'automotive-engineering': 'fahrzeugtechnik',
  'chemical-engineering': 'verfahrenstechnik',
  'biomedical-engineering': 'medizintechnik',
  'materials-science': 'materialwissenschaft',
  'robotics-mechatronics': 'mechatronik-robotik',
  'energy-engineering': 'energietechnik',
  'industrial-engineering': 'wirtschaftsingenieurwesen',
  architecture: 'architektur',
  'urban-planning': 'raumplanung',
  'industrial-design': 'produktdesign',
  'game-design': 'game-design',
  'ux-design': 'ux-design',
  medicine: 'medizin',
  nursing: 'pflege',
  pharmacy: 'pharmazie',
  dentistry: 'zahnmedizin',
  'veterinary-medicine': 'veterinaermedizin',
  physiotherapy: 'physiotherapie',
  'sports-science': 'sportwissenschaft',
  nutrition: 'ernaehrungswissenschaft',
  'public-health': 'public-health',
  psychology: 'psychologie',
  economics: 'volkswirtschaftslehre',
  'business-management': 'betriebswirtschaft',
  'finance-accounting': 'finance-rechnungswesen',
  marketing: 'marketing',
  entrepreneurship: 'entrepreneurship',
  logistics: 'logistik',
  'hospitality-tourism': 'tourismus-hotellerie',
  'political-science': 'politikwissenschaft',
  law: 'rechtswissenschaft',
  criminology: 'kriminologie',
  sociology: 'soziologie',
  anthropology: 'ethnologie',
  'social-work': 'soziale-arbeit',
  education: 'paedagogik',
  journalism: 'journalismus',
  'media-communication': 'medien-kommunikation',
  history: 'geschichte',
  archaeology: 'archaeologie',
  philosophy: 'philosophie',
  'religious-studies': 'theologie',
  linguistics: 'linguistik',
  languages: 'sprachen-uebersetzen',
  literature: 'literatur',
  'liberal-arts': 'liberal-arts',
  'fine-arts': 'bildende-kunst',
  'graphic-design': 'grafikdesign',
  'fashion-design': 'modedesign',
  'film-production': 'film',
  'animation-vfx': 'animation',
  music: 'musik',
  'music-production': 'musikproduktion',
  'performing-arts': 'theater-tanz',
  'culinary-arts': 'kulinarik',
  agriculture: 'agrarwissenschaften',
  aviation: 'aviatik',
}

export const FIELD_ID_BY_SLUG_DE: Record<string, string> = Object.fromEntries(Object.entries(FIELD_SLUG_DE).map(([id, slug]) => [slug, id]))

export const fieldSlugDe = (id: string) => FIELD_SLUG_DE[id] ?? id
